### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gangliao** [rust-lang/rust-clippy#8189] opened 2021-12-28 22:01 UTC
```bash
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', compiler/rustc_query_impl/src/on_disk_cache.rs:500:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.59 (f8abed9 2021-12-26)

query stack during panic:
#0 [typeck] type-checking `driver::funcgen::function::tests::lambda_function_name`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `flock`
```

**Comment by camsteffen** [comment] 2021-12-28 22:04
Most likely a duplicate of rust-lang/rust#92163

**Closed by camsteffen** 2021-12-28 22:04 UTC
