### ISSUE TITLE
internal compiler error: unexpected panic with clippy 0.1.58

### ISSUE THREAD

**Issue by michidk** [rust-lang/rust-clippy#8340] opened 2022-01-23 21:03 UTC
After renaming my struct `DocumentParser` to `OffDocument` (https://github.com/michidk/off-rs/blob/clippy_err/src/parser/mod.rs#L19) with vscode and rust-analyzer, clippy panics.

Edit: Happens with every new name. 

```
PS C:\Users\michi\development\private\off-rs> cargo clippy
    Checking off-rs v0.1.0 (C:\Users\michi\development\private\off-rs)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\compiler\rustc_hir\src\definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.58 (02072b48 2022-01-11)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

# How to replicate

Clone https://github.com/michidk/off-rs/tree/clippy_err (`clippy_errr` branch)
Run `cargo clippy` (version: clippy 0.1.58 (02072b48 2022-01-1)

**Comment by michidk** [comment] 2022-01-23 21:06
Actually, I am not sure if this is an issue with just clippy, since `cargo build` also panics.

**Comment by giraffate** [comment] 2022-01-24 00:22
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust/issues/90682.

**Comment by giraffate** [comment] 2022-01-28 02:36
It's the rustc issue, so I'm closing this.

**Closed by giraffate** 2022-01-28 02:36 UTC
