### ISSUE TITLE
Remove range_plus_one lint?

### ISSUE THREAD

**Issue by devashishdxt** [rust-lang/rust-clippy#4988] opened 2020-01-03 06:18 UTC
Here's the reason why using it is bad sometimes.

https://www.reddit.com/r/rust/comments/eiwhkn/why_is_iterator_so_much_faster/fctvmt4?utm_source=share&utm_medium=web2x

**Comment by sinkuu** [comment] 2020-01-03 09:41
Duplicate of https://github.com/rust-lang/rust-clippy/issues/2217.

**Closed** 2020-01-03 14:54 UTC
