### ISSUE TITLE
redundant_field_names can't be allowed

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rust-clippy#5515] opened 2020-04-23 17:40 UTC
Hello.

I do like to write `Foo { bar: bar }` and I don't like to write `Foo { bar }`.
So I'm trying to turn off the "redundant_field_names" lint:

```
#![cfg_attr(feature = "cargo-clippy", allow(redundant_field_names))]
```
but it has no effect, I'm still getting spammed by this lint.

Please help.

Rust version: 1.44.0-beta.752

**Comment by dtolnay** [comment] 2020-04-23 18:13
Duplicate of #5356.

**Closed** 2020-04-23 21:27 UTC

**Comment by e-oz** [comment] 2020-05-26 17:39
Please merge this, 1.44.0-beta.4 and still this bug.

**Comment by e-oz** [comment] 2020-06-03 19:36
Thank you very much, works fine in 1.45.0-beta.3359
