### ISSUE TITLE
Print with newline edge cases

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust-clippy#2295] opened 2017-12-23 16:26 UTC
I ran clippy on https://github.com/diesel-rs/diesel/pull/1428 and it gave the following warnings:

```
error: using `print!()` with a format string that ends in a newline, consider using `println!()` instead
  --> src/comment.rs:28:9
   |
28 |         print!("===============\n\n");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> src/main.rs:1:9
   |
1  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: #[deny(print_with_newline)] implied by #[deny(warnings)]
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.177/index.html#print_with_newline

error: using `print!()` with a format string that ends in a newline, consider using `println!()` instead
  --> src/post.rs:56:5
   |
56 |     print!("\n");
   |     ^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.177/index.html#print_with_newline
```

These are not *wrong* but also not helpful: We want to explicitly write a number of new lines.

**Comment by sgrif** [comment] 2018-01-02 21:47
Hilariously, I only wrote `print!("\n")` over `println!("")` because I could have sworn clippy complained on empty string to `println!`

**Comment by killercup** [comment] 2018-01-03 20:28
> I could have sworn clippy complained on empty string to println!

It wants you to use `println!();`. Let me open an issue to add a suggestion for that: #2319.

**Comment by Areredify** [comment] 2020-01-23 19:38
duplicate of #2990, can now be closed @flip1995

**Closed** 2020-01-23 19:41 UTC
