### ISSUE TITLE
Panic while running cargo clippy

### ISSUE THREAD

**Issue by InfRandomness** [rust-lang/rust-clippy#8531] opened 2022-03-13 00:18 UTC
I am experiencing this panic while running cargo clippy on this crate : https://gitlab.com/veloren/veloren/-/tree/master/world
```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:179:90: Failed to normalize <std::option::Option<&std::option::Option<usize>> as std::iter::Iterator>::Item, maybe try to call `try_normalize_erasing_regions` instead

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1236:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.61 (5f4e067 2022-03-10)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `veloren-world`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by llogiq** [comment] 2022-03-13 20:06
On what operating system are you running, and what version of rustc do you use?

**Comment by giraffate** [comment] 2022-03-14 00:24
It might be a duplicate of https://github.com/rust-lang/rust/issues/93946.

**Comment by InfRandomness** [comment] 2022-03-14 07:42
I am using nightly-2022-03-11, so rustc 1.59.0 on openSUSE Tumbleweed

**Comment by InfRandomness** [comment] 2022-03-17 16:36
https://github.com/rust-lang/rust/issues/95021
Appears to say that the issue has been resolved, is the release of clippy in 2022-03-17 using the 2022-03-17 rustc?

**Comment by giraffate** [comment] 2022-03-24 00:23
FYI Clippy has been synced into rust-lang/rust every about two weeks like this: https://github.com/rust-lang/rust/pull/94929

**Comment by InfRandomness** [comment] 2022-03-24 07:37
So next one is in about next week ?

**Comment by giraffate** [comment] 2022-03-25 00:13
That's just what's being done: https://github.com/rust-lang/rust/pull/95273

**Comment by InfRandomness** [comment] 2022-03-25 18:39
The issue seems to have disappeared on nightly-2022-03-24

**Comment by InfRandomness** [comment] 2022-04-04 11:32
Has there been a regression on this ? 
Issue seems to happen again

**Comment by giraffate** [comment] 2022-04-04 12:54
It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/8527, so I'm closing this.

**Closed by giraffate** 2022-04-04 12:54 UTC
Labels: I-ICE
