### ISSUE TITLE
Extend `useless_format` to lint values other than `&str` and `String`

### ISSUE THREAD

**Issue by mikerite** [rust-lang/rust-clippy#3753] opened 2019-02-10 04:34 UTC
`format!("{}", x)` can be replaced by `x.to_string()` when `x` implements [`ToString`](https://doc.rust-lang.org/std/string/trait.ToString.html) . The new code is neater and probably faster.

**Comment by sinkuu** [comment] 2019-02-10 09:32
`format!("{}", x)` can be unconditionally rewritten to `x.to_stirng()` thanks to the `<T: Display> ToString for T` blanket impl.

**Comment by oli-obk** [comment] 2019-02-10 09:41
@ralfj mentioned that they really dislike even changing `format!("foo")` to `"foo".to_string()` considering that they have the same perf nowadays and readability does not suffer at all. Quite the opposite: if you have 20 format! calls in a file and a few `to_string` sprinkled in between, that actually is worse than just having `format!` everywhere

**Comment by RalfJung** [comment] 2019-02-10 10:24
Addendum: I dislike this in some cases. I think this is context-dependent.  I use `format!` when this is similar to other nearby code (e.g. formatting error messages for the user, and there are a whole bunch of cases) -- consistency in multiple match branches increases readability a lot.

But when the intention is not to format user-visible text, but to e.g. turn an integer into a string, I will use `i.to_string()`.  I think there is a different in intent between formatting and converting to a string, and it is useful to express that in the code.

**Comment by mikerite** [comment] 2019-02-11 05:18
Good point about `<T:Display>`.

So would this change be accepted? If not, should we do anything about the existing lint?

**Comment by sanmai-NL** [comment] 2019-02-15 08:41
So, 
```rust
format!("foo")
```
is worse at communicating intention than
```rust
"foo".to_owned()
```

**Comment by RalfJung** [comment] 2019-02-15 08:58
That depends heavily on the context.

In Miri, we have some error types taking `String`, and then you frequently see code like
```rust
MachineError(format!("Unable to access {}", foobar))
```
but sometimes the message is just a string with no format variable, and then we write
```rust
MachineError(format!("Division by 0"))
```
I think this communicates intent much clearer than if we changed *some* of the error messages to use `to_owned`.

**Comment by sanmai-NL** [comment] 2019-02-15 09:01
I think you're confusing consistency and/or the principle of least surprise with communicating intent there. And I happen to value the latter more than stylistic consistency.

**Comment by RalfJung** [comment] 2019-02-15 09:33
Well, feel free to turn on that lint in your files then, but please don't make add it to a default lint.

And no, I don't think I am confusing this. The intent here is to create a string for consumption by the user -- the intent is to do formatting for UI output. The fact that the string being printed is a literal should not mean that I suddenly use entirely different syntax.  The fact that the string must be owned to be put into a `MachineError` is a detail I couldn't care less about at this point, so `to_owned` conveys to useful information in this case.

**Comment by sanmai-NL** [comment] 2019-02-15 09:57
But you're not formatting that literal at all in the case we're talking about. You would use an `&str` if you could, you just need to assert ownership of it.

**Comment by camsteffen** [comment] 2021-11-15 17:41
Duplicate of #3156

**Closed by camsteffen** 2021-11-15 17:41 UTC
Labels: good-first-issue, A-lint, L-pedantic
