### ISSUE TITLE
assigning_clones: Suggestion conflicts with borrow checker

### ISSUE THREAD

**Issue by adamreichold** [rust-lang/rust-clippy#12444] opened 2024-03-09 09:58 UTC
### Summary

Nightly Clippy started suggesting usage of `clone_into` but applying the suggesting conflicts with the borrow checker because an immutable borrow of the target variable exists. Assigning works because the borrow ends after the clone is done and hence before the assignment.

### Reproducer

I started with the warning:

```console
warning: assigning the result of `ToOwned::to_owned()` may be inefficient
   --> harvester/src/uvp_verbund.rs:169:33
    |
169 | ...                   name = last.to_owned();
    |                       ^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_into()`: `last.clone_into(&mut name)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
```

and after applying the suggestion got:

```console
error[E0502]: cannot borrow `name` as mutable because it is also borrowed as immutable
   --> harvester/src/uvp_verbund.rs:169:49
    |
161 |                         let parts = name.split(", ").collect::<Vec<_>>();
    |                                     ---- immutable borrow occurs here
...
169 |                                 last.clone_into(&mut name);
    |                                      ---------- ^^^^^^^^^ mutable borrow occurs here
    |                                      |
    |                                      immutable borrow later used by call
```

The full code is available [here](https://gitlab.opencode.de/umwelt-info/metadaten/-/blob/e85780d842cac2356e9082a9e889babdb4191e1a/harvester/src/uvp_verbund.rs#L159-L175).

### Version

```text
rustc 1.78.0-nightly (46b180ec2 2024-03-08)
binary: rustc
commit-hash: 46b180ec2452d388c5d9c14009442e2e0beb01d7
commit-date: 2024-03-08
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

**Comment by Kobzol** [comment] 2024-03-12 15:59
This is a minimal reproducer:
```rust
fn foo(mut name: String) {
    let parts = name.split(", ").collect::<Vec<_>>();
    let first = *parts.first().unwrap();
    name = first.to_owned();
    //first.clone_into(&mut name);
}
```
I guess that the issue is that in `first.to_owned()`, the `first` reference is not alive once `name` is reassigned (?). While in the second case, both references need to live during the method call, which causes the issue.

I have no idea how to detect these situations though. @blyxyas any ideas? :)

**Comment by y21** [comment] 2024-05-02 21:00
I think for this we should be able to use [`PossibleBorrowerMap`](https://doc.rust-lang.org/stable/nightly-rustc/clippy_utils/mir/struct.PossibleBorrowerMap.html). That can tell us that `first` borrows from `name` and we can safely bail out if so.
I've been looking into this issue for a bit so I can give this a try. 
@rustbot claim

**Closed** 2024-06-15 18:34 UTC
Labels: C-bug, I-suggestion-causes-error
