### ISSUE TITLE
New internal error on nightly-2022-11-10

### ISSUE THREAD

**Issue by nik9000** [rust-lang/rust-clippy#9845] opened 2022-11-13 19:54 UTC
### Summary

Sorry I don't have a minimal example! But I was able to bisect the problem to the release on nightly-2022-11-10. I don't know rust at all so I'm sure I'm writing some non-canonical thing patterns. I'd be happy to try and make a reproduction if there was some way to get a hint of where to start. I looked at the Bug Minimization Patterns and didn't have a whole lot of luck on my side.

### Version

```text
rustc 1.67.0-nightly (42325c525 2022-11-11)
binary: rustc
commit-hash: 42325c525b9d3885847a3f803abe53c562d289da
commit-date: 2022-11-11
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
thread '<unnamed>' panicked at 'forcing query with already existing `DepNode`
- query-key: Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder(TraitPredicate(<impl AsRef<Path> as std::convert::AsRef<std::path::Path>>, polarity:Positive), []), Binder(TraitPredicate(<impl AsRef<Path> as std::convert::AsRef<std::path::Path>>, polarity:Positive), []), Binder(TraitPredicate(<impl AsRef<Path> as std::marker::Sized>, polarity:Positive), []), Binder(TraitPredicate(<impl AsRef<Path> as std::marker::Sized>, polarity:Positive), [])], reveal: UserFacing, constness: NotConst }, value: Binder(TraitPredicate(<for<'a, 'b, 'c> {std::future::ResumeTy, &'a mut io::Reader, &'b mut io::Reader, io::number::u8::ReadFutureExistentialType<'c>, ()} as std::marker::Send>, polarity:Positive), []) } }
- dep-node: evaluate_obligation(45f62b07ddc68da5-65c244439a958d00)', /rustc/42325c525b9d3885847a3f803abe53c562d289da/compiler/rustc_query_system/src/dep_graph/graph.rs:316:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/42325c525b9d3885847a3f803abe53c562d289da/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/42325c525b9d3885847a3f803abe53c562d289da/library/core/src/panicking.rs:65:14
   2: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::evaluate_obligation, rustc_query_impl::plumbing::QueryCtxt>
   3: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
   4: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
   5: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_all_or_error
   6: rustc_trait_selection::traits::fully_solve_bound
   7: <clippy_lints::future_not_send::FutureNotSend as rustc_lint::passes::LateLintPass>::check_fn
   8: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn
   9: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_fn
  10: rustc_hir::intravisit::walk_impl_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  11: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_impl_item
  12: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  13: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  14: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  15: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  16: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  17: rustc_lint::late::late_lint_pass_crate::<rustc_lint::late::LateLintPassObjects>
  18: rustc_lint::late::late_lint_crate::<rustc_lint::BuiltinCombinedLateLintPass>
  19: <rustc_session::session::Session>::time::<(), rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  20: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  21: <core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#5}::{closure#1}> as core::ops::function::FnOnce<()>>::call_once
  22: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}>
  23: rustc_interface::passes::analysis
  24: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  26: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  27: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  28: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  29: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  30: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

  ```

  </p>
</details>

**Comment by nik9000** [comment] 2022-11-13 19:54
> `rustc 1.67.0-nightly (42325c525 2022-11-11)`

Looks like the problem first appeared in 2022-11-10.

**Comment by Chralt98** [comment] 2022-11-14 08:59
I am experiencing the same with `nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.67.0-nightly (6284998a2 2022-11-12)`.

Seems to be solved with `nightly-aarch64-apple-darwin unchanged - rustc 1.67.0-nightly (e631891f7 2022-11-13)`. Although it's another machine (linux to macos), but I had the same error on MacOS before the update to `e631891f7`.

**Comment by xFrednet** [comment] 2024-07-17 20:56
Without a minimum reproducible example this is hard to investigate. The comment from `@Chralt98` seems to indicate that this was fixed. Otherwise, it was suggested that this is a duplicate of https://github.com/rust-lang/rust-clippy/issues/9846

Therefore, I'll close this for now. If you still have this issue, please create a new issue. You can also link a repo with the bug

**Closed by xFrednet** 2024-07-17 20:56 UTC
Labels: C-bug, I-ICE
