### ISSUE TITLE
field_reassign_with_default: Suggestion does not work in case of private fields

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/rust-clippy#6481] opened 2020-12-20 10:58 UTC
```rust
    let mut server_config = ServerConfig::default();
    server_config.transport = Arc::new(transport_config);
```
```
warning: field assignment outside of initializer for an instance created with Default::default()
   --> src/server/network.rs:168:5
    |
168 |     server_config.transport = Arc::new(transport_config);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(clippy::field_reassign_with_default)]` on by default
note: consider initializing the variable with `quinn::generic::ServerConfig<quinn::crypto::rustls::TlsSession> { transport: Arc::new(transport_config), ..Default::default() }` and removing relevant reassignments
   --> src/server/network.rs:167:5
    |
167 |     let mut server_config = ServerConfig::default();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#field_reassign_with_default
```

So I changed it to:
```rust
    let server_config = ServerConfig {
        transport: Arc::new(transport_config),
        ..Default::default()
    };
```
But got:
```
error[E0451]: field `token_key` of struct `quinn::generic::ServerConfig` is private
   --> src/server/network.rs:169:11
    |
169 |         ..Default::default()
    |           ^^^^^^^^^^^^^^^^^^ field `token_key` is private

error[E0451]: field `use_stateless_retry` of struct `quinn::generic::ServerConfig` is private
   --> src/server/network.rs:169:11
    |
169 |         ..Default::default()
    |           ^^^^^^^^^^^^^^^^^^ field `use_stateless_retry` is private

error[E0451]: field `retry_token_lifetime` of struct `quinn::generic::ServerConfig` is private
   --> src/server/network.rs:169:11
    |
169 |         ..Default::default()
    |           ^^^^^^^^^^^^^^^^^^ field `retry_token_lifetime` is private

error[E0451]: field `accept_buffer` of struct `quinn::generic::ServerConfig` is private
   --> src/server/network.rs:169:11
    |
169 |         ..Default::default()
    |           ^^^^^^^^^^^^^^^^^^ field `accept_buffer` is private

error[E0451]: field `migration` of struct `quinn::generic::ServerConfig` is private
   --> src/server/network.rs:169:11
    |
169 |         ..Default::default()
    |           ^^^^^^^^^^^^^^^^^^ field `migration` is private

```

### Meta

- `cargo clippy -V`: clippy 0.0.212 (1c389ff 2020-11-24)
- `rustc -Vv`:
 ```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
binary: rustc
commit-hash: 1c389ffeff814726dec325f0f2b0c99107df2673
commit-date: 2020-11-24
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
 ```

**Comment by xFrednet** [comment] 2020-12-20 16:41
Here is an example [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b010eea7c66a65e3d47f1aa5fc525bb6) that triggers the same lint :)

**Comment by giraffate** [comment] 2020-12-20 23:37
Thanks for your report!

I'm closing this as duplicate of https://github.com/rust-lang/rust-clippy/issues/6344.

**Closed by giraffate** 2020-12-20 23:37 UTC
Labels: L-bug, L-false-positive, L-suggestion-causes-error
