### ISSUE TITLE
cargo-clippy unconditionally runs lints for path dependencies

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-clippy#1066] opened 2016-07-02 15:53 UTC
Say we have this project:

Cargo.toml:

``` toml
[package]
name = "haspathdep"
version = "0.1.0"

[features]
clippy = []

[dependencies.foodep]
path = "foodep"

```

src/lib.rs:

``` rust
extern crate foodep;

#[cfg_attr(feature="clippy", allow(enum_variant_names))]
enum Sock {
    YellowSock,
}

pub fn utilize() {
    let _sock = Sock::YellowSock;
    let _spr = foodep::Sprite::ASprite;
}

```

foodep/Cargo.toml:

``` toml
[package]
name = "foodep"
version = "0.1.0"

[features]
clippy = []

```

foodep/src/lib.rs:

``` rust
// Triggers `enum_variant_names` lint.
// Let's just say I have no control over the naming,
// as this is a -sys crate generated with bindgen.
#[cfg_attr(feature="clippy", allow(enum_variant_names))]
pub enum Sprite {
    ASprite,
    BSprite,
}

```

When I run `cargo clippy --features=clippy` on `foodep`, it compiles without warnings, because of the conditional `allow(enum_variant_names)`.

However, when I run `cargo clippy --features=clippy` on `haspathdep`, it also runs the clippy lints for `foodep`, but without taking into consideration that I have enabled `--features=clippy`.

```
$ cargo clippy --features=clippy
   Compiling foodep v0.1.0 (file:///tmp/haspathdep/foodep)
foodep/src/lib.rs:6:5: 6:12 warning: Variant name ends with the enum's name, #[warn(enum_variant_names)] on by default
foodep/src/lib.rs:6     ASprite,
                        ^~~~~~~
foodep/src/lib.rs:6:5: 6:12 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#enum_variant_names
foodep/src/lib.rs:7:5: 7:12 warning: Variant name ends with the enum's name, #[warn(enum_variant_names)] on by default
foodep/src/lib.rs:7     BSprite,
                        ^~~~~~~
foodep/src/lib.rs:7:5: 7:12 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#enum_variant_names
foodep/src/lib.rs:5:1: 8:2 warning: All variants have the same postfix: `Sprite`, #[warn(enum_variant_names)] on by default
foodep/src/lib.rs:5 pub enum Sprite {
                    ^
foodep/src/lib.rs:5:1: 8:2 help: remove the postfixes and use full paths to the variants instead of glob imports
foodep/src/lib.rs:5:1: 8:2 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#enum_variant_names
   Compiling haspathdep v0.1.0 (file:///tmp/haspathdep)

```

**Comment by anderejd** [comment] 2018-10-02 07:58
Clippy seems to be running on all path dependencies again, reopen this issue?

**Comment by oli-obk** [comment] 2018-11-20 19:06
That's just a hack to detect that we're in the final `rustc` invocation of `cargo check`. `cargo check` runs `rustc` for all dependencies (where we don't want to lint) and then at the end runs `rustc` for the final crate (where we inject our lints).

I want to build a general way for custom drivers to be run on the final crate only (and without such flag parsing hacks), but I haven't gotten around to it.

**Comment by steveklabnik** [comment] 2019-06-17 21:52
Ran into this today, and found it very surprising.

**Comment by Manishearth** [comment] 2019-06-17 21:55
The permanent fix for this is https://github.com/rust-lang/rust-clippy/issues/3837, once we have that we can customize this behavior in cargo.

**Comment by nrc** [comment] 2019-07-23 21:14
> I want to build a general way for custom drivers to be run on the final crate only (and without such flag parsing hacks), but I haven't gotten around to it.

If this is still the problem blocking fixing this, then there is a solution to use the Cargo API - there is a `Command` API which gives a way to distinguish the final/main crate from deps. (I don't recall the details, but the RLS uses it).

**Comment by ehuss** [comment] 2019-07-23 21:28
This is fixed on latest master of cargo for `clippy-preview` (via rust-lang/cargo#7069).  I'll be updating nightly soon.  Migrating to clippy-preview is tracked in #3837.

**Comment by yaahallo** [comment] 2019-07-24 02:17
Ooh god, I accidentally fixed an issue I participated in a year earlier without even knowing. That's fun.

**Closed** 2019-07-24 07:16 UTC
Labels: L-bug :beetle:

**Comment by dvc94ch** [comment] 2020-01-02 19:04
I think there's been a regression
```sh
cargo-clippy --version
clippy 0.0.212 (c8e3cfb 2019-10-28)
```

**Comment by flip1995** [comment] 2020-01-02 20:01
You have to use `clippy-preview`, which is the cargo integrated (unstable) version of Clippy. We hope, that this will be the default soon.

**Comment by notoria** [comment] 2020-05-24 20:06
I'm using `clippy` version `clippy 0.0.212 (28197b6 2020-04-29)` with:
```
$ rustc -vV
rustc 1.45.0-nightly (fa51f810e 2020-04-29)
binary: rustc
commit-hash: fa51f810e5b9254904b92660e7280b7d6a46f112
commit-date: 2020-04-29
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```
I have a project with one path dependency (`foo = { path = "../foo" }`) and `clippy` always lints it.
And `#[allow(clippy::all)]` doesn't solved my issue. How can I do it right?

**Comment by ryanavella** [comment] 2020-11-19 16:37
I'm seeing the same thing as @notoria. Am I missing something?

```
> rustc -vV
rustc 1.50.0-nightly (825637983 2020-11-18)
binary: rustc
commit-hash: 8256379832b5ecb7f71e8c5e2018446482223c12
commit-date: 2020-11-18
host: x86_64-pc-windows-msvc
release: 1.50.0-nightly

> rustup -V
rustup 1.22.1 (b01adbbc3 2020-07-08)

> cargo-clippy -V
clippy 0.0.212 (82563798 2020-11-18)

> rustup component add clippy-preview
info: component 'clippy' for target 'x86_64-pc-windows-msvc' is up to date
```

**Comment by ehuss** [comment] 2020-11-23 14:34
@ryanavella Use `cargo +nightly clippy -Zunstable-options`, see https://github.com/rust-lang/rust-clippy/issues/3837#issuecomment-617413116.
