### ISSUE TITLE
panicked at 'index out of bounds: the len is 1 but the index is 1', src/tools/clippy/clippy_lints/src/repeat_once.rs:44:93

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust-clippy#6147] opened 2020-10-09 07:59 UTC
This worked fine with 1.46 but not anymore after the update to 1.47 (clippy 0.0.212 (18bf6b4 2020-10-07))

Happens when running

```sh
cargo clippy -- -A clippy::redundant_pattern_matching -A clippy::single_match -A clippy::cast_lossless -A clippy::missing_safety_doc -D warnings
```

in `gstreamer-sdp` at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/

Full backtrace:

```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', src/tools/clippy/clippy_lints/src/repeat_once.rs:44:93
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:62
   3: <clippy_lints::repeat_once::RepeatOnce as rustc_lint::passes::LateLintPass>::check_expr
   4: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_expr
   5: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   6: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   7: rustc_hir::intravisit::walk_expr
   8: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
   9: rustc_hir::intravisit::walk_expr
  10: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  11: rustc_hir::intravisit::walk_expr
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  13: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  14: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  15: rustc_hir::intravisit::walk_impl_item
  16: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  17: rustc_hir::intravisit::walk_item
  18: rustc_hir::intravisit::Visitor::visit_nested_item
  19: rustc_hir::intravisit::walk_item
  20: rustc_hir::intravisit::Visitor::visit_nested_item
  21: rustc_hir::intravisit::walk_crate
  22: rustc_lint::late::late_lint_pass_crate
  23: rustc_lint::late::late_lint_crate
  24: rustc_data_structures::sync::join
  25: rustc_session::utils::<impl rustc_session::session::Session>::time
  26: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  27: rustc_session::utils::<impl rustc_session::session::Session>::time
  28: rustc_interface::passes::analysis
  29: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  30: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::get_query_impl
  34: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  35: rustc_span::with_source_map
  36: rustc_interface::interface::create_compiler_and_run
  37: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (18bf6b4 2020-10-07)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `gstreamer-sdp`.
```

**Comment by sdroege** [comment] 2020-10-09 08:03
This was fixed by https://github.com/rust-lang/rust-clippy/pull/5948 but it unfortunately did not end up in 1.47.

**Comment by flip1995** [comment] 2020-10-09 08:13
Closing since it was already fixed, so nothing we can do here.

A Clippy ICE is not enough to do a point release of rust stable. But if there should be one, we'll try to get the fix in.

**Closed by flip1995** 2020-10-09 08:13 UTC

**Comment by sdroege** [comment] 2020-10-09 08:16
Well, it's annoying because it prevents me from updating CI configurations to 1.47 :) And especially annoying because beta and nightly never failed with this.

**Comment by sdroege** [comment] 2020-10-09 09:01
Just to be sure, I realize that doing a point release is a lot of work and it probably doesn't matter for such a thing but I'm probably also not the only one running into this. Sucks, but that's life :)

Is there a way to disable running that lint completely btw? `-A clippy::repeat_once` still runs it.

**Comment by flip1995** [comment] 2020-10-09 09:15
> Just to be sure, I realize that doing a point release is a lot of work and it probably doesn't matter for such a thing but I'm probably also not the only one running into this.

Yeah, this bug slipped through, but sadly now it's too late. I think there is a point release planned, since also a regression fix in the compiler is planned. But there isn't an ETA yet.

> Is there a way to disable running that lint completely btw?

No sadly not. Renaming the `repeat` method fixes the issue, which would be a workaround. But I don't know if that is applicable for you. Sorry for the inconvenience!

**Comment by sdroege** [comment] 2020-10-09 09:41
> Yeah, this bug slipped through, but sadly now it's too late. I think there is a point release planned, since also a regression fix in the compiler is planned. But there isn't an ETA yet.

That's good to know, thanks :)

> No sadly not. Renaming the `repeat` method fixes the issue, which would be a workaround. But I don't know if that is applicable for you.

Unfortunately not as that would be an API change.

> Sorry for the inconvenience!

No worries, such things happen. Annoying for everybody involved but that's just how it is :)

**Comment by flip1995** [comment] 2020-10-09 11:38
I prepared a stable backport in https://github.com/rust-lang/rust/pull/77750. So if there is a point release, this should get backported :+1:
