### ISSUE TITLE
Issue with map(clone) on Option in latest nightly

### ISSUE THREAD

**Issue by amircodota** [rust-lang/rust-clippy#12148] opened 2024-01-14 07:26 UTC
### Summary

I'm getting many many clippy warnings in the latest nightly.

They all stem from the fact that I'm using the `map` method on an `Option` to invoke a clone method on some intenral part of the value, but not on the entire Option value. Clippy tells me to just clone the entire option variable.

Here are a few examples

```
warning: this call to `as_ref.map(...)` does nothing
  --> base/git_utils/src/git_stats.rs:98:24
   |
98 |             repo_name: git_url.as_ref().map(|git_url| git_url.name.clone()),
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `git_url.clone()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_asref
   = note: `#[warn(clippy::useless_asref)]` on by default
```

```
warning: this call to `as_ref.map(...)` does nothing
  --> shared/models_api_singleton/src/lib.rs:67:37
   |
67 |                 update_access_token(user_option.as_ref().map(|user| user.id_token.clone()));
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `user_option.clone()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_asref
   = note: `#[warn(clippy::useless_asref)]` on by default
```

```
warning: this call to `as_ref.map(...)` does nothing
   --> tabnine/lunar_connection/src/lib.rs:948:40
    |
948 |     if let Some(Some(log_file_path)) = process.as_ref().map(|p| p.log_file_path().clone()) {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `process.clone()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_asref
    = note: `#[warn(clippy::useless_asref)]` on by default
```

### Reproducer

I tried this code:

```rust
<code>
```

I expected to see this happen:

Instead, this happened:

### Version

```text
cargo 1.77.0-nightly (84976cd69 2024-01-12)
```

**Comment by y21** [comment] 2024-01-14 13:29
Duplicate of #12135. #12136 fixes this.

**Comment by nazar-pc** [comment] 2024-01-19 14:06
I don't think it was fixed yet, still happening on latest nightly:
```
clippy 0.1.77 (25f8d01 2024-01-18)
```

**Comment by y21** [comment] 2024-01-19 14:09
The fix is not in nightly yet. Clippy gets synced with upstream rust only every ~14 days, so it'll be in nightly on the 25th. (The fix was merged 5 days ago but the last sync was on the 11th)

**Comment by amircodota** [comment] 2024-01-26 06:21
Still happens to me on the latest nightly

**Closed** 2024-01-26 17:13 UTC
Labels: C-bug
