### ISSUE TITLE
ptr_arg

### ISSUE THREAD

**Issue by silence-code** [rust-lang/rust-clippy#5278] opened 2020-03-06 04:41 UTC
may be is specific type

**Comment by silence-code** [comment] 2020-03-06 04:42
Why is this bad
Requiring the argument to be of the specific size makes the function less useful for no benefit; slices in the form of &[T] or &str usually suffice and can be obtained from other types, too.

**Comment by silence-code** [comment] 2020-03-06 04:43
![截图](https://user-images.githubusercontent.com/59049248/76053409-0f0ee400-5fa8-11ea-82b0-3898c56887e9.png)

**Comment by flip1995** [comment] 2020-03-09 13:39
I don't really understand what the issue here is. Is it the documentation, the lint itself or something else?

**Comment by flip1995** [comment] 2020-03-10 21:00
ping from triage @silence-code. I'm closing this issue, since it is not clear if and what the issue is here.

**Closed by flip1995** 2020-03-10 21:00 UTC
