### ISSUE TITLE
New lint: Replace `Result::map(|_| ())` or `map(|_| {})` with `map(drop)`

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust-clippy#5001] opened 2020-01-06 07:47 UTC
In https://github.com/rust-lang/rust/issues/67672, people suggest to replace
the toilet closure (`|_| ()` or `|_| {}`) with the `drop` fn.

**Comment by flip1995** [comment] 2020-01-06 16:11
Duplicate of #2523

**Closed by flip1995** 2020-01-06 16:11 UTC
Labels: A-complexity, L-lint
