### ISSUE TITLE
suggested changes should not expand `format!` to `$crate::fmt::format($crate::__export::format_args!`

### ISSUE THREAD

**Issue by tdyas** [rust-lang/rust-clippy#6838] opened 2021-03-04 07:03 UTC
Code in question:

```rust
error: manual implementation of `Option::map`
    --> rule_graph/src/builder.rs:1166:9
     |
1166 | /         if let Some(errors) = errored.get(&node_id) {
1167 | |           Some(format!("{}:\n{}", node, errors.join("\n")))
1168 | |         } else {
1169 | |           None
1170 | |         }
     | |_________^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_map
help: try this
     |
1166 |         errored.get(&node_id).map(|errors| {
1167 |         let res = $crate::fmt::format($crate::__export::format_args!($($arg)*));
1168 |         res
1169 |     })
     |
```

I expected the suggested change to keep `format!` the same and to not expand it to `$crate::fmt::format($crate::__export::format_args!`.

### Meta

```
cargo 1.52.0-nightly (bf5a5d5e5 2021-02-18)
release: 1.52.0
commit-hash: bf5a5d5e5d3ae842a63bfce6d070dfd438cf6070
commit-date: 2021-02-18
```

This happens with `rustc` as of `6f7673d077add6b9a066e988b1b8b132a8193d6c`. (Dumping the version would not be helpful since the copy of rustc in question contains a local reversion from tracking down an unrelated ICE that I had encountered, just documenting this issue as I saw it).

**Comment by matthiaskrgr** [comment] 2021-03-04 07:10
Thanks, this is a duplicate of https://github.com/rust-lang/rust-clippy/issues/6811 which has already been fixed in https://github.com/rust-lang/rust-clippy/pull/6801 but the change has not landed in rustc tarballs yet.
Closing.

**Closed by matthiaskrgr** 2021-03-04 07:10 UTC
Labels: C-bug
