### ISSUE TITLE
Cargo recompile after running clippy

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust-clippy#1281] opened 2016-10-14 23:37 UTC
Hello.
When I run `cargo clippy`, followed by `cargo build`, the crate will be recompiled (by the `cargo build` command) even if it was not updated.
It would be nice that running `cargo clippy` does not result in a recompilation for the next `cargo build` if nothing was changed.
Thanks to fix this.

**Comment by mcarton** [comment] 2016-10-14 23:54
This is expected? `cargo clippy` will always use a nightly compiler under the hood, but `cargo build` might not. Also `cargo clippy` compiles with `-Zno-trans`, which means that nothing actually gets compiled.

**Comment by antoyo** [comment] 2016-10-14 23:58
I use the nightly compiler.
Here is the output of this issue:
```
$ rustup default nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.14.0-nightly (a7bfb1aba 2016-10-09)

$ cargo build
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
$ cargo clippy
   Compiling test v0.1.0 (file:///path/to/project)
    Finished debug [unoptimized + debuginfo] target(s) in 0.15 secs
$ cargo build
   Compiling test v0.1.0 (file:///path/to/project)
    Finished debug [unoptimized + debuginfo] target(s) in 0.33 secs
```

**Comment by oli-obk** [comment] 2016-10-17 07:13
The problem is `cargo rustc`, because we forward `cargo clippy` to `cargo rustc`. So this should be a bug report against cargo, since we can't do anything about it on our end.

**Comment by oli-obk** [comment] 2016-10-17 07:14
Well... we could make `cargo clippy` actually build the target, but that would slow down `cargo clippy` significantly.

**Comment by antoyo** [comment] 2016-10-17 12:20
Thanks for your answer.
I opened an [issue](https://github.com/rust-lang/cargo/issues/3204).

**Comment by flip1995** [comment] 2020-08-24 23:39
That shouldn't happen. Can you post a reproducer?

I will close this issue, since the thing the issue talks about is expected and won't change. Feel free to post the reproducer here or open a new issue.

**Closed by flip1995** 2020-08-24 23:39 UTC
