### ISSUE TITLE
Clippy reports "thread 'rustc' panicked at 'begin <= end (19 <= 6) when slicing"

### ISSUE THREAD

**Issue by skyscribe** [rust-lang/rust-clippy#7457] opened 2021-07-13 05:13 UTC
Detailed error:

thread 'rustc' panicked at 'begin <= end (19 <= 6) when slicing `x == '}' || x == '{' || x == ' ' || x == '\t' || x == '\r' || x == '\n'`', src/tools/clippy/clippy_lints/src/functions/too_many_lines.rs:24:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Same compilation source code with cargo test/cargo run works.

**Comment by giraffate** [comment] 2021-07-13 06:05
Can you provide a minimal reproduction on the playground?

**Comment by Jarcho** [comment] 2021-07-17 17:41
This was fixed in #7287 going by the line number.

**Comment by giraffate** [comment] 2021-07-19 14:14
I'm closing this because of https://github.com/rust-lang/rust-clippy/issues/7457#issuecomment-881933208.

**Closed by giraffate** 2021-07-19 14:14 UTC
