### ISSUE TITLE
installation failed with  ` cannot find tuple struct/variant `ItemTraitAlias` in module `hir``

### ISSUE THREAD

**Issue by asaadmohammed74** [rust-lang/rust-clippy#2276] opened 2017-12-17 22:32 UTC
i tried to install clippy with `cargo install clippy` but i get this

```
~$ cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading clippy v0.0.176                                                    
  Installing clippy v0.0.176                                                    
 Downloading cargo_metadata v0.2.3
 Downloading clippy_lints v0.0.176                                              
 Downloading matches v0.1.6                                                     
 Downloading quine-mc_cluskey v0.2.4                                            
 Downloading if_chain v0.1.2                                                    
 Downloading itertools v0.6.5                                                   
 Downloading url v1.6.0                                                         
 Downloading unicode-normalization v0.1.5                                       
 Downloading pulldown-cmark v0.0.15                                             
 Downloading either v1.4.0                                                      
 Downloading idna v0.1.4                                                        
 Downloading percent-encoding v1.0.1                                            
 Downloading unicode-bidi v0.3.4                                                
   Compiling if_chain v0.1.2                                                    
   Compiling matches v0.1.6
   Compiling libc v0.2.34
   Compiling quote v0.3.15
   Compiling num-traits v0.1.41
   Compiling regex-syntax v0.4.1
   Compiling pulldown-cmark v0.0.15
   Compiling clippy v0.0.176
   Compiling dtoa v0.4.2
   Compiling serde v1.0.24
   Compiling quine-mc_cluskey v0.2.4
   Compiling lazy_static v1.0.0
   Compiling unicode-xid v0.0.4
   Compiling void v1.0.2
   Compiling semver-parser v0.7.0
   Compiling utf8-ranges v1.0.0
   Compiling bitflags v0.9.1
   Compiling getopts v0.2.15
   Compiling percent-encoding v1.0.1
   Compiling itoa v0.3.4
   Compiling unicode-normalization v0.1.5
   Compiling either v1.4.0
   Compiling unicode-bidi v0.3.4
   Compiling memchr v2.0.1
   Compiling toml v0.4.5
   Compiling synom v0.11.3
   Compiling unreachable v1.0.0
   Compiling semver v0.6.0
   Compiling serde_json v1.0.8
   Compiling itertools v0.6.5
   Compiling aho-corasick v0.6.4
   Compiling idna v0.1.4
   Compiling syn v0.11.11
   Compiling thread_local v0.3.5
   Compiling url v1.6.0
   Compiling regex v0.2.3
   Compiling serde_derive_internals v0.18.0
   Compiling serde_derive v1.0.24
   Compiling clippy_lints v0.0.176
   Compiling cargo_metadata v0.2.3
error[E0531]: cannot find tuple struct/variant `ItemTraitAlias` in module `hir`
   --> /home/asaadmohammed74/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.176/src/utils/inspector.rs:406:14
    |
406 |         hir::ItemTraitAlias(..) => {
    |              ^^^^^^^^^^^^^^ not found in `hir`

error[E0531]: cannot find tuple struct/variant `ItemTraitAlias` in module `hir`
   --> /home/asaadmohammed74/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.176/src/missing_doc.rs:132:18
    |
132 |             hir::ItemTraitAlias(..) => "a trait alias",
    |                  ^^^^^^^^^^^^^^ not found in `hir`

error[E0599]: no variant named `TraitAlias` found for type `rustc::hir::def::Def` in the current scope
   --> /home/asaadmohammed74/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.176/src/utils/mod.rs:943:9
    |
943 |         Def::TraitAlias(id) |
    |         ^^^^^^^^^^^^^^^^^^^ variant not found in `rustc::hir::def::Def`

error: aborting due to 3 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.176`, intermediate artifacts can be found at `/tmp/cargo-install.p6iw6dIIopJD`

Caused by:
  build failed
```

```
rustc 1.24.0-nightly (2d4df9584 2017-12-10)
cargo 0.25.0-nightly (930f9d949 2017-12-05)
```

**Comment by killercup** [comment] 2017-12-17 23:17
You need to update your nightly version: https://github.com/rust-lang-nursery/rust-clippy/commit/8ddcb81a15d6d186a71e7954d709ac94cbb7b718

**Comment by phansch** [comment] 2018-12-11 15:38
Closing this as this was caused by an old Clippy/nightly mismatch.

**Closed by phansch** 2018-12-11 15:38 UTC
