### ISSUE TITLE
match_same_arms: suppress when reordering arms?

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust-clippy#1140] opened 2016-08-05 09:38 UTC
`match_same_arms` will not consider the order of match arms.

Since it is specified that arms are checked in order, this leads to suggestions with two potential problems:
- less optimal performance, when expensive arm conditions are checked too early
- changes in semantics

Example for the latter:

```
fn main() {
    let x = match 2 {
        1 ... 3 => false,
        0 ... 5 => true,
        _ => false
    };
}
```

If this seems bad anyway because of overlap, consider the slightly more complex

```
fn main() {
    let y = 1;
    let x = match 2 {
        1 ... 3 => false,
        0 ... 5 if y == 2 => true,
        _ => false
    };
}
```

**Comment by oli-obk** [comment] 2016-08-05 11:13
We can try to analyze whether order changes don't change semantics. A simple analysis would probably assume that only the order of different enum variants is irrelevant or the order of non overlapping int patterns

**Comment by Arnavion** [comment] 2021-06-17 23:41
Duplicate of #860, though that one initially meandered into an unrelated discussion and this one has a more realistic example.

**Closed** 2022-03-21 20:58 UTC
