### ISSUE TITLE
I ran cargo clippy and this showed up

### ISSUE THREAD

**Issue by Alumin112** [rust-lang/rust-clippy#8081] opened 2021-12-06 10:22 UTC
```
    Checking othello v0.1.0 (/home/alumin112/Desktop/Rust/othello)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.57 (f1edd04 2021-11-29)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `othello`
```

**Comment by giraffate** [comment] 2021-12-06 13:53
It's duplicate of https://github.com/rust-lang/rust-clippy/issues/8076, so I'm closing this.

**Closed by giraffate** 2021-12-06 13:53 UTC
