### ISSUE TITLE
Copy types being used in RefCell

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#439] opened 2015-11-06 00:05 UTC
What it says on the tin.

I'm not sure if we should be linting against AST types (which is easy), or against the internal types of expressions (which may end up getting false positives when being passed to a method expecting a generic refcell)

**Comment by oli-obk** [comment] 2016-05-12 15:10
dupe of #1

**Comment by Areredify** [comment] 2020-02-02 00:43
ping @flip1995

**Closed** 2020-02-02 00:45 UTC
Labels: C-needs-discussion, L-lint, T-middle
