### ISSUE TITLE
meta-lint: dump info on types and statements

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1234] opened 2016-09-19 15:57 UTC
I'm going to write a lint that we can use to more easily analyze pieces of code that we are going to write code for.
- if `#[clippy_dump]` is attached to any item/statement, the item is printed in a structured way
- data printed
  - shallow ast (EarlyLintPass)
  - shallow hir (LateLintPass)
  - type
  - if the attribute is added to a type's declaration (or a typedef)
    - all traits implemented by the type
    - all inherent methods on the type
    - memory representation
  - if the attribute is added to a typedef
    - location of the original type
  - if the attribute is added to a statement defining a closure
    - full list of things the closure borrows/owns
- "shallow" meaning that the printing needs to stop at the first inner block (inside which attributes can be used again, to print more)

Open questions:
- configuration for the attribute to select what kind of data to dump
- more info to be dumped?

**Comment by Manishearth** [comment] 2016-09-19 16:35
+1

(btw, no need to use C-assigned when you're assigning yourself; C-assigned is used to make up for Github's inability to assign to non-collaborators. Though feel free to use it if you like, doesn't make much of a difference 😄 )

**Comment by oli-obk** [comment] 2016-09-20 09:00
labels need a description xD half the time I have no clue what they mean

**Comment by mcarton** [comment] 2016-09-20 13:25
> labels need a description xD half the time I have no clue what they mean

We could add that in the contributing.md file:

> * Green-ish, **A**-prefixed labels state which **area** of the project an issue relates to.
* Dark-blue, **T**-prefixed labels state which **type** of lint this issue is about. `T-AST` lints are purely syntactic and generaly only match some [AST nodes](https://en.wikipedia.org/wiki/Abstract_syntax_tree). `T-middle` are more involved and might need to lookup types or resolve constant expressions.
* Green, Yellow and Read, **E**-prefixed labels explain the level of **experience** necessary to fix the issue. Generally an issue marked `T-middle` is harder than an issue marked `T-AST` for the same `E` level.
* Pinkish, **L**-prefixed labels explain what the issue is asking for or reporting.

Adapted from https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md. I admit I haven't found what the **C** and **L** prefixes stand for either :sweat_smile:
Also, I don't really see a difference between `C-needs-discussion` and `question`.

**Comment by camsteffen** [comment] 2021-11-13 21:30
This is pretty well covered by `-Z unpretty` and `clippy::author`.

**Closed by camsteffen** 2021-11-13 21:30 UTC
Labels: E-medium, T-middle, S-needs-discussion, C-an-interesting-project
