### ISSUE TITLE
Pedantic lint against `unreachable!()`

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust-clippy#4959] opened 2019-12-26 12:56 UTC
It would be nice to have a lint, that detects any use of the [`unreachable!`](https://doc.rust-lang.org/1.3.0/std/macro.unreachable!.html) macro without arguments.

This is useful for procedural macros, where only the following is shown
```
error: proc-macro derive panicked
 --> tests/test_union.rs:3:10
  |
3 | #[derive(ShortHand)]
  |          ^^^^^^^^^
  |
  = help: message: internal error: entered unreachable code

error: aborting due to previous error

error: could not compile `shorthand`.

To learn more, run the command again with --verbose.
```
This is fine, if you only have one or two uses of `unreachable`, but it becomes very difficult in larger codebases, because you have to check every occurrence of `unreachable` in the codebase.

Adding some text to the macro will  be a lot more helpful!
`unreachable!("ident is neither enable nor disable")`
```
error: proc-macro derive panicked
 --> tests/test_union.rs:3:10
  |
3 | #[derive(ShortHand)]
  |          ^^^^^^^^^
  |
  = help: message: internal error: entered unreachable code: ident is neither enable nor disable

error: aborting due to previous error

error: could not compile `shorthand`.

To learn more, run the command again with --verbose.
```

I think `panic!` in a proc-macro has the same issue.

**Comment by flip1995** [comment] 2019-12-28 12:09
Easy extension of #4657

**Comment by chansuke** [comment] 2020-01-03 03:04
I'd like to work on this issue

**Comment by flip1995** [comment] 2020-01-03 17:03
I just realized, that this lint already exists, but is allow-by-default (and will stay that way). So you have to enable it with `#[warn(clippy::unreachable)]`. The only thing, I can think of on how to improve this lint, is to add a configuration option to disable the lint if an explanation is provided. Would that help?

**Comment by Luro02** [comment] 2020-01-03 17:05
I think the opposite would be better, add a lint, that will warn if `unreachable!` has no explanation?

**Comment by flip1995** [comment] 2020-01-03 17:09
That lint already exists. But it warns regardless of if `unreachable!` has an explanation or not. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=80c900c6310ede6426eaea1ceef400e3)

**Comment by flip1995** [comment] 2020-01-08 16:41
Just realized, that an issue exists for this (the lint doesn't trigger, when a message is passed) 

Duplicate of #3528

**Closed by flip1995** 2020-01-08 16:41 UTC
Labels: L-lint, good first issue
