### ISSUE TITLE
False positive assertions_on_constants

### ISSUE THREAD

**Issue by MikailBag** [rust-lang/rust-clippy#5064] opened 2020-01-18 17:20 UTC
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=40fdbfbe2885aeb26531533ee38b450f

While expression can be compile-time evaluated to `true`, it can make sense to be sure that `Foo` will always be  smaller that `Bar`.

**Comment by JohnTitor** [comment] 2020-01-20 02:42
Uhm, I feel this isn't false positive, but expected behavior. It's an appropriate approach to use `panic!()`, `unreachable!()`, or similar functions/macros.

**Comment by flip1995** [comment] 2020-01-20 11:41
It is expected behavior, how the lint is currently written. A possible change would be to allow comparisons in asserts (only `<`,`<=`,`>=`,`>`, for the rest there is `*_eq`/`*_ne`). We could then add a pedantic lint, that also triggers on comparisons, since this is still a useful lint. 

The question now is: Is the lint still useful once comparisons are not linted? Because then it pretty much only lints on literal `true`/`false`.

**Comment by mikerite** [comment] 2020-01-20 12:11
Maybe continue to lint in the `false` case but allow the `true` one since it's useful for documenting assumptions.

**Comment by flip1995** [comment] 2021-12-23 12:06
Duplicate of #8159 , which has some more details.

**Closed by flip1995** 2021-12-23 12:06 UTC
