### ISSUE TITLE
Panic for out-of-bounds, not reproducible with a clean build

### ISSUE THREAD

**Issue by dodomorandi** [rust-lang/rust-clippy#8243] opened 2022-01-08 15:58 UTC
```
thread 'rustc' panicked at 'index out of bounds: the len is 361 but the index is 372', compiler/rustc_query_impl/src/on_disk_cache.rs:726:18
stack backtrace:
   0:     0x7f262d3c0b4c - std::backtrace_rs::backtrace::libunwind::trace::hac89ae696ab31153
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f262d3c0b4c - std::backtrace_rs::backtrace::trace_unsynchronized::he0e34c1ffcd1fd95
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f262d3c0b4c - std::sys_common::backtrace::_print_fmt::hbbcd6534ff2cdaab
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f262d3c0b4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hca373cbf95c63dfd
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f262d42168c - core::fmt::write::hf1bd4152e956a546
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/core/src/fmt/mod.rs:1168:17
   5:     0x7f262d3afec3 - std::io::Write::write_fmt::h2f14a980b941fea5
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/io/mod.rs:1660:15
   6:     0x7f262d3c5012 - std::sys_common::backtrace::_print::hc99e12058f69fd7f
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f262d3c5012 - std::sys_common::backtrace::print::h28ddbd216cc47c63
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f262d3c5012 - std::panicking::default_hook::{{closure}}::h91763e160bca83d2
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/panicking.rs:211:50
   9:     0x7f262d3c4bf5 - std::panicking::default_hook::h04e711875c06f41e
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/panicking.rs:228:9
  10:     0x55fb9091fa01 - clippy_driver[de939f5069ad0877]::ICE_HOOK::{closure#0}::{closure#0}
  11:     0x7f2617950273 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h381580d40f238f7a
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/alloc/src/boxed.rs:1868:9
  12:     0x7f261795c91d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h259534c2c6987d0c
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7f262d3c57c5 - std::panicking::rust_panic_with_hook::h7d6693789c82cfe4
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/panicking.rs:610:17
  14:     0x7f262d3c54c0 - std::panicking::begin_panic_handler::{{closure}}::ha2fa99da9c892fdb
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/panicking.rs:502:13
  15:     0x7f262d3c0ff4 - std::sys_common::backtrace::__rust_end_short_backtrace::h6aa583a96333c408
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/sys_common/backtrace.rs:139:18
  16:     0x7f262d3c51f9 - rust_begin_unwind
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/panicking.rs:498:5
  17:     0x7f262d38cec1 - core::panicking::panic_fmt::h5b13621b08c43b42
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/core/src/panicking.rs:107:14
  18:     0x7f262d38ce82 - core::panicking::panic_bounds_check::h0627500a7a09ab0d
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/core/src/panicking.rs:75:5
  19:     0x7f262f562d55 - <rustc_span[5840c952fc6dfb1f]::span_encoding::Span as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  20:     0x7f262f55f63b - <rustc_middle[6a5313df6756a06b]::ty::VariantDef as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  21:     0x7f262f521f67 - <rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder as rustc_serialize[f019258c4fd3540d]::serialize::Decoder>::read_seq::<alloc[c6e5149209dd10d4]::vec::Vec<rustc_middle[6a5313df6756a06b]::ty::VariantDef>, <alloc[c6e5149209dd10d4]::vec::Vec<rustc_middle[6a5313df6756a06b]::ty::VariantDef> as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode::{closure#0}>
  22:     0x7f262ffc52c7 - <rustc_middle[6a5313df6756a06b]::ty::adt::AdtDef as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  23:     0x7f262f5068bb - <rustc_middle[6a5313df6756a06b]::ty::sty::TyKind as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  24:     0x7f262f5586b1 - <&rustc_middle[6a5313df6756a06b]::ty::TyS as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7f262f55857b - <&rustc_middle[6a5313df6756a06b]::ty::TyS as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  26:     0x7f262f526ad6 - <rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder as rustc_serialize[f019258c4fd3540d]::serialize::Decoder>::read_map::<std[e740e8867e95a171]::collections::hash::map::HashMap<rustc_hir[b6231e5dfc545669]::hir_id::ItemLocalId, &rustc_middle[6a5313df6756a06b]::ty::TyS, core[24291291a921b533]::hash::BuildHasherDefault<rustc_hash[e86116ee62a311f2]::FxHasher>>, <std[e740e8867e95a171]::collections::hash::map::HashMap<rustc_hir[b6231e5dfc545669]::hir_id::ItemLocalId, &rustc_middle[6a5313df6756a06b]::ty::TyS, core[24291291a921b533]::hash::BuildHasherDefault<rustc_hash[e86116ee62a311f2]::FxHasher>> as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode::{closure#0}>
  27:     0x7f262ffc5561 - <rustc_middle[6a5313df6756a06b]::ty::context::TypeckResults as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode::{closure#0}
  28:     0x7f262ffc45a6 - <&rustc_middle[6a5313df6756a06b]::ty::context::TypeckResults as rustc_serialize[f019258c4fd3540d]::serialize::Decodable<rustc_query_impl[e097f5d713df899a]::on_disk_cache::CacheDecoder>>::decode
  29:     0x7f262ffe2e19 - <rustc_query_impl[e097f5d713df899a]::on_disk_cache::OnDiskCache>::try_load_query_result::<&rustc_middle[6a5313df6756a06b]::ty::context::TypeckResults>
  30:     0x7f262ff1b7e1 - rustc_query_system[1b2734a6ce8acad3]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt, rustc_span[5840c952fc6dfb1f]::def_id::LocalDefId, &rustc_middle[6a5313df6756a06b]::ty::context::TypeckResults>
  31:     0x7f262f487b18 - rustc_query_system[1b2734a6ce8acad3]::query::plumbing::try_execute_query::<rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt, rustc_query_system[1b2734a6ce8acad3]::query::caches::DefaultCache<rustc_span[5840c952fc6dfb1f]::def_id::LocalDefId, &rustc_middle[6a5313df6756a06b]::ty::context::TypeckResults>>
  32:     0x7f262f4fc15c - <rustc_query_impl[e097f5d713df899a]::Queries as rustc_middle[6a5313df6756a06b]::ty::query::QueryEngine>::typeck
  33:     0x7f262f912499 - <rustc_middle[6a5313df6756a06b]::ty::context::TyCtxt>::typeck_body
  34:     0x7f262f209872 - rustc_mir_build[5910af347b55be5b]::thir::pattern::check_match::check_match
  35:     0x7f263001eb7c - <rustc_query_system[1b2734a6ce8acad3]::dep_graph::graph::DepGraph<rustc_middle[6a5313df6756a06b]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6a5313df6756a06b]::ty::context::TyCtxt, rustc_span[5840c952fc6dfb1f]::def_id::DefId, ()>
  36:     0x7f262ff8cdb6 - rustc_data_structures[bfaea707c82a54c9]::stack::ensure_sufficient_stack::<((), rustc_query_system[1b2734a6ce8acad3]::dep_graph::graph::DepNodeIndex), rustc_query_system[1b2734a6ce8acad3]::query::plumbing::execute_job<rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt, rustc_span[5840c952fc6dfb1f]::def_id::DefId, ()>::{closure#3}>
  37:     0x7f262f49c6e1 - rustc_query_system[1b2734a6ce8acad3]::query::plumbing::try_execute_query::<rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt, rustc_query_system[1b2734a6ce8acad3]::query::caches::DefaultCache<rustc_span[5840c952fc6dfb1f]::def_id::DefId, ()>>
  38:     0x7f262f4fc8aa - <rustc_query_impl[e097f5d713df899a]::Queries as rustc_middle[6a5313df6756a06b]::ty::query::QueryEngine>::check_match
  39:     0x7f262ee23db3 - <core[24291291a921b533]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[947fac54d3fe2868]::passes::analysis::{closure#1}::{closure#0}> as core[24291291a921b533]::ops::function::FnOnce<()>>::call_once
  40:     0x7f262fa87b88 - <rustc_session[c20293ac279aad06]::session::Session>::time::<(), rustc_interface[947fac54d3fe2868]::passes::analysis::{closure#1}>
  41:     0x7f262fa61f8e - rustc_interface[947fac54d3fe2868]::passes::analysis
  42:     0x7f2630029456 - <rustc_query_system[1b2734a6ce8acad3]::dep_graph::graph::DepGraph<rustc_middle[6a5313df6756a06b]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6a5313df6756a06b]::ty::context::TyCtxt, (), core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>
  43:     0x7f262ff856d3 - rustc_data_structures[bfaea707c82a54c9]::stack::ensure_sufficient_stack::<(core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_query_system[1b2734a6ce8acad3]::dep_graph::graph::DepNodeIndex), rustc_query_system[1b2734a6ce8acad3]::query::plumbing::execute_job<rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt, (), core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>::{closure#3}>
  44:     0x7f262ff06de6 - rustc_query_system[1b2734a6ce8acad3]::query::plumbing::try_execute_query::<rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt, rustc_query_system[1b2734a6ce8acad3]::query::caches::DefaultCache<(), core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>>
  45:     0x7f262ff5fcf5 - rustc_query_system[1b2734a6ce8acad3]::query::plumbing::get_query::<rustc_query_impl[e097f5d713df899a]::queries::analysis, rustc_query_impl[e097f5d713df899a]::plumbing::QueryCtxt>
  46:     0x7f262fa42f30 - <rustc_interface[947fac54d3fe2868]::interface::Compiler>::enter::<rustc_driver[aab467f4c82ed6ad]::run_compiler::{closure#1}::{closure#2}, core[24291291a921b533]::result::Result<core[24291291a921b533]::option::Option<rustc_interface[947fac54d3fe2868]::queries::Linker>, rustc_errors[62a5cc7b06393f71]::ErrorReported>>
  47:     0x7f262fa24c3c - rustc_span[5840c952fc6dfb1f]::with_source_map::<core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_interface[947fac54d3fe2868]::interface::create_compiler_and_run<core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_driver[aab467f4c82ed6ad]::run_compiler::{closure#1}>::{closure#1}>
  48:     0x7f262fa4230e - rustc_interface[947fac54d3fe2868]::interface::create_compiler_and_run::<core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_driver[aab467f4c82ed6ad]::run_compiler::{closure#1}>
  49:     0x7f262fa2619b - <scoped_tls[ec1705c99dfa8720]::ScopedKey<rustc_span[5840c952fc6dfb1f]::SessionGlobals>>::set::<rustc_interface[947fac54d3fe2868]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[947fac54d3fe2868]::interface::run_compiler<core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_driver[aab467f4c82ed6ad]::run_compiler::{closure#1}>::{closure#0}, core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>::{closure#0}::{closure#0}, core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>
  50:     0x7f262fa25f95 - std[e740e8867e95a171]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[947fac54d3fe2868]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[947fac54d3fe2868]::interface::run_compiler<core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_driver[aab467f4c82ed6ad]::run_compiler::{closure#1}>::{closure#0}, core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>::{closure#0}, core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>
  51:     0x7f262fa528a9 - <<std[e740e8867e95a171]::thread::Builder>::spawn_unchecked<rustc_interface[947fac54d3fe2868]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[947fac54d3fe2868]::interface::run_compiler<core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>, rustc_driver[aab467f4c82ed6ad]::run_compiler::{closure#1}>::{closure#0}, core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>::{closure#0}, core[24291291a921b533]::result::Result<(), rustc_errors[62a5cc7b06393f71]::ErrorReported>>::{closure#1} as core[24291291a921b533]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:     0x7f262d3d0cf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9a9713b5d2e24fc2
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/alloc/src/boxed.rs:1854:9
  53:     0x7f262d3d0cf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9651309876a3c2bf
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/alloc/src/boxed.rs:1854:9
  54:     0x7f262d3d0cf3 - std::sys::unix::thread::Thread::new::thread_start::h8f346e0de1984669
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154/library/std/src/sys/unix/thread.rs:108:17
  55:     0x7f262d2d1259 - start_thread
  56:     0x7f262d0b45e3 - __GI___clone
  57:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.59 (e012a19 2022-01-06)

query stack during panic:
#0 [typeck] type-checking `surface::<impl at sdl/src/surface.rs:245:1: 261:2>::create_rgb::{closure#0}`
#1 [check_match] match-checking `surface::<impl at sdl/src/surface.rs:245:1: 261:2>::create_rgb::{closure#0}`
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `sdl`
```

I encountered the issue while compiling [this commit](https://github.com/dodomorandi/freedroid-rs/commit/983d7236e557c590ec66fb36bd5af5cef144f503) on my hobby project. Unfortunately (or not, depending on the point of view) it does not reproduce with a clean rebuild.

I am using rust-analyzer configured for running `cargo clippy` instead of `cargo check`, I don't know if it could have caused some issues with the cache.

**Comment by giraffate** [comment] 2022-01-13 23:45
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/8255, so I'm closing this.

**Closed by giraffate** 2022-01-13 23:45 UTC
