### ISSUE TITLE
Suggestion to remove redudant implied stdlib traits

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#6673] opened 2021-02-04 13:06 UTC
On code similar to this:

```rust
fn foo<T: Ord + Eq>(x: T, y: T) {
    if x < y {
        println!();
    }
}
fn main() {}
```

Clippy could suggest to remove the standard library trait "+ Eq" because it's already implied by "Ord".

**Comment by giraffate** [comment] 2021-02-04 23:27
Thanks for the suggestion of the new lint! But, I'm closing this because it's a duplicate of https://github.com/rust-lang/rust-clippy/issues/1488.

**Closed by giraffate** 2021-02-04 23:27 UTC
Labels: L-lint
