### ISSUE TITLE
Conflicting with rustc lints

### ISSUE THREAD

**Issue by uselessgoddess** [rust-lang/rust-clippy#9313] opened 2022-08-09 17:22 UTC
I tried use `unreachable_pub` from rustc and `redundant_pub_crate` from clippy. I get a cyclical contradiction.

```rust
#![deny(unreachable_pub)]
#![deny(clippy::redundant_pub_crate)]

pub(crate) mod internal1 {
    pub(crate) fn foo() {}
}

pub(crate) mod internal2 {
    pub fn foo() {}
}
```

```
error: pub(crate) function inside private module
 --> src\main.rs:5:5
  |
5 |     pub(crate) fn foo() {}
  |     ----------^^^^^^^
  |     |
  |     help: consider using: `pub`
  |

error: unreachable `pub` item
 --> src\main.rs:9:5
  |
9 |     pub fn foo() {}
  |     ---^^^^^^^^^
  |     |
  |     help: consider restricting its visibility: `pub(crate)`
  |

```
rustc suggest use `pub fn foo`
clippy suggest use `pub(crate) fn foo`

### Version

```text
rustc 1.65.0-nightly (f03ce3096 2022-08-08)
binary: rustc
commit-hash: f03ce30962cf1b2a5158667eabae8bf6e8d1cb03
commit-date: 2022-08-08
host: x86_64-pc-windows-msvc
release: 1.65.0-nightly
LLVM version: 14.0.6
```

**Comment by Jarcho** [comment] 2022-08-17 01:04
Duplicate of #8005

**Closed by Jarcho** 2022-08-17 01:04 UTC
Labels: C-bug
