### ISSUE TITLE
clippy crashes due to SIGABRT

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/rust-clippy#8514] opened 2022-03-07 20:04 UTC
### Summary

I encountered the following crash during `cargo clippy`: 
```
$ RUST_BACKTRACE=1 cargo clippy
<snip>
error: could not compile `my_crate`

Caused by:
  process didn't exit successfully: `/Users/me/.rustup/toolchains/stable-x86_64-apple-darwin/bin/clippy-driver rustc --crate-name my_crate --edition=2018 my_crate/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,future-incompat --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=05eb530c0c2d2b19 -C extra-filename=-05eb530c0c2d2b19 --out-dir /Users/me/work/myproject/target/debug/deps -C incremental=/Users/me/work/myproject/target/debug/incremental -L dependency=/Users/me/work/myproject/target/debug/deps --extern async_broadcast=/Users/me/work/myproject/target/debug/deps/libasync_broadcast-cddaacd669deaf09.rmeta --extern chrono=/Users/me/work/myproject/target/debug/deps/libchrono-258669bd10c57f7c.rmeta --extern common=/Users/me/work/myproject/target/debug/deps/libcommon-8165fad6b35a233f.rmeta --extern http=/Users/me/work/myproject/target/debug/deps/libhttp-cebb379ccc9d7ea3.rmeta --extern libh3=/Users/me/work/myproject/target/debug/deps/liblibh3-a57a19da91b131c5.rmeta --extern rand=/Users/me/work/myproject/target/debug/deps/librand-8ba3f5b249f6fc6c.rmeta --extern serde=/Users/me/work/myproject/target/debug/deps/libserde-8f2a8085b0cf1c56.rmeta --extern serde_json=/Users/me/work/myproject/target/debug/deps/libserde_json-fd36b80b76661ecb.rmeta --extern smol=/Users/me/work/myproject/target/debug/deps/libsmol-adaff9b789fc3d1f.rmeta --extern tracing=/Users/me/work/myproject/target/debug/deps/libtracing-edaf3a4ca9d1b0de.rmeta -C target-cpu=native -L native=/Users/me/work/myproject/target/debug/build/ring-5b87ea3e17bf5e12/out -L native=/Users/me/work/myproject/target/debug/build/quiche-b003d1a2b3f6ee91/out/build/` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Version

```text
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-apple-darwin
release: 1.59.0
LLVM version: 13.0.0
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  No backtrace shown.
  ```

  </p>
</details>

**Comment by lilyball** [comment] 2022-03-07 21:13
This looks like #8470. If you copy the `clippy-driver` command and run it manually, do you get an error like this?

```
clippy-driver(17833,0x70001050a000) malloc: *** error for object 0x60000372a200: pointer being realloc'd was not allocated
clippy-driver(17833,0x70001050a000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by keepsimple1** [comment] 2022-03-07 23:28
Yes, when I ran the `clippy-driver` command manually, I got a similar error: 
```
clippy-driver(40900,0x700002c59000) malloc: *** error for object 0x600003e7da00: pointer being realloc'd was not allocated
clippy-driver(40900,0x700002c59000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by giraffate** [comment] 2022-03-08 00:25
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/8470, so I'm closing this.

**Closed by giraffate** 2022-03-08 00:25 UTC
Labels: C-bug, I-ICE
