### ISSUE TITLE
Syntax highlighting for code snippets on the lints website is broken

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust-clippy#13559] opened 2024-10-17 21:57 UTC
Go to the [lints website](https://rust-lang.github.io/rust-clippy/master/index.html), and you'll see how code examples are shown with almost the same color as the background. It's very hard to read them this way.

![Image](https://github.com/user-attachments/assets/bc469f89-f32e-4edd-9d34-58e06d3c6f07)

All the color themes are affected except it's a bit less critical with the light ones. However, code snippets still have no syntax highlighting with the light theme. They are displayed as monotone black text:

![Image](https://github.com/user-attachments/assets/af630158-08b9-493b-a3c9-4714a03fec56)

**Comment by y21** [comment] 2024-10-17 22:10
Closing as a duplicate of #13536. This will be fixed by #13539.

**Closed by y21** 2024-10-17 22:10 UTC
