### ISSUE TITLE
Possible bug in the `identity_conversion` lint.

### ISSUE THREAD

**Issue by Sean1708** [rust-lang/rust-clippy#4236] opened 2019-06-26 13:54 UTC
If it's not a bug then I think the error message should probably be improved, because I have absolutely no idea what it's trying to tell me.

I've got a (hopefully short enough) MWE here:

```
$ cargo clippy -V         
clippy 0.0.212 (265318d 2019-05-17)
$ tree
.
├── Cargo.toml
└── src
    └── main.rs

1 directory, 2 files
$ cat Cargo.toml 
[package]
name = "clippy_mwe"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
$ cat src/main.rs 
fn main() {
        print_paths().unwrap();
}

fn maybe_get_iter(v: &[f64]) -> Result<impl Iterator<Item=&f64>, usize> {
        if v.len() > 1 {
                Ok(v.iter())
        } else {
                Err(v.len())
        }
}

fn print_paths() -> Result<(), u64> {
        let v = vec![1.0, 2.0, 3.0, 4.0];
        for path in maybe_get_iter(&v).map_err(|e| e as u64)? {
                println!("{:?}", path);
        }

        Ok(())
}
$ cargo run
   Compiling clippy_mwe v0.1.0 (/tmp/tmp.sA6y5tSSr9/clippy_mwe)
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/clippy_mwe`
1.0
2.0
3.0
4.0
$ cargo clippy
    Checking clippy_mwe v0.1.0 (/tmp/tmp.sA6y5tSSr9/clippy_mwe)
warning: identical conversion
  --> src/main.rs:15:14
   |
15 |     for path in maybe_get_iter(&v).map_err(|e| e as u64)? {
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider removing `maybe_get_iter(&v).map_err(|e| e as u64)?()`: `maybe_get_iter(&v).map_err(|e| e as u64)?`
   |
   = note: #[warn(clippy::identity_conversion)] on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_conversion

    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
```

From my experimentation so far it looks like you need a function that returns an iterator as the `Ok` variant of a `Result`, to use `map_err` on that result, _and then_ to use the `?` operator. If you don't have all three of those things then `clippy` seems to be fine with it.

**Comment by flip1995** [comment] 2019-06-26 14:43
Duplicate of #4207 #4183 #4133 #3913 ... 😄 

This is already fixed in Clippy master / nightly and probably beta. In stable Clippy it will be available at 4th of July.

If you have the latest Clippy and you still get this FP, feel free to reopen!

**Closed by flip1995** 2019-06-26 14:43 UTC

**Comment by Sean1708** [comment] 2019-06-26 16:41
Ah thanks. I checked the open tickets but forgot to check closed ones, sorry!
