### ISSUE TITLE
Got a `rustc` panic, filing a bug report as requested

### ISSUE THREAD

**Issue by kyp44** [rust-lang/rust-clippy#7454] opened 2021-07-12 03:12 UTC
When I run `cargo clippy` on my project I get the following error, though I have resolved all lints, and the project builds fine normally:

```
thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.55 (7a16cfc 2021-07-11)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

I'm just filing a report per the request in the error message.

The project I am working on is just working through the [Advent of Code](https://adventofcode.com/) problems to help me become competent in Rust. I don't currently have the project on GitHub or anything, but, if it would help you reproduce this issue, I'd be happy to post it. Also don't hesitate to ask if there's any other info I can provide that would be useful to you.

I am using the nightly channel in `rustup` if that makes a difference.

**Comment by giraffate** [comment] 2021-07-12 03:49
Thanks for the report!

I'm closing this because it's duplicate of https://github.com/rust-lang/rust-clippy/issues/7423.

**Closed by giraffate** 2021-07-12 03:49 UTC
