### ISSUE TITLE
could not compiler winapi

### ISSUE THREAD

**Issue by woodgear** [rust-lang/rust-clippy#3505] opened 2018-12-07 06:28 UTC
cargo clippy -V
clippy 0.0.212 (29bf75cd 2018-12-05)

error 
```
$ cargo clippy --verbose
    Checking winapi v0.3.6
     Running `C:\Users\developer\.rustup\toolchains\nightly-i686-pc-windows-msvc\bin\clippy-driver.exe rustc --crate-name winapi 'C:\Users\developer\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\lib.rs' --color always --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=2171991fceccb3fc -C extra-filename=-2171991fceccb3fc --out-dir 'C:\Users\developer\Desktop\test_clippy\target\debug\deps' -L 'dependency=C:\Users\developer\Desktop\test_clippy\target\debug\deps' --cap-lints allow`
error: Could not compile `winapi`.

Caused by:
  process didn't exit successfully: `C:\Users\developer\.rustup\toolchains\nightly-i686-pc-windows-msvc\bin\clippy-driver.exe rustc --crate-name winapi 'C:\Users\developer\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src\lib.rs' --color always --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=2171991fceccb3fc -C extra-filename=-2171991fceccb3fc --out-dir 'C:\Users\developer\Desktop\test_clippy\target\debug\deps' -L 'dependency=C:\Users\developer\Desktop\test_clippy\target\debug\deps' --cap-lints allow`(exit code: 3221225477)

```
```
[package]
name = "test_clippy"
version = "0.1.0"
edition = "2018"

[dependencies]
winapi = "0.3.6"
```
```
use winapi::*;
fn main() {
    println!("Hello, world!");
}
```

**Comment by matthiaskrgr** [comment] 2018-12-07 09:16
This looks weird...
Does `cargo check` work on the package?

**Comment by mati865** [comment] 2018-12-07 09:40
Duplicate of https://github.com/rust-lang/rust-clippy/issues/2310 or https://github.com/rust-lang/rust-clippy/issues/3202
Possibly related https://github.com/rust-lang/rust-clippy/issues/3345

**Comment by phansch** [comment] 2018-12-11 18:14
Closing as duplicate.

**Closed by phansch** 2018-12-11 18:14 UTC
