### ISSUE TITLE
new lint: suggest .iter().filter() instead of  if .. { continue; }  inside loops

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-clippy#4234] opened 2019-06-25 20:30 UTC
````rust
fn a() {
    let r = 0..10;
    for i in r {
        if i % 2 == 0 {
            continue;
        }
        print!("{} ", i);
    }
}
````
In this code where the first statement inside the loop body is a condition-guarded `continue` statement, we could replace the `if cond { continue;}` branch with a more idiomatic .iter().filter() call:
````rust
fn b() {
    let r = 0..10;
    for i in r.filter(|i| i % 2 != 0) {
        print!("{} ", i);
    }
}
````

**Comment by oli-obk** [comment] 2019-06-26 09:09
Duplicate of https://github.com/rust-lang/rust-clippy/issues/678

**Closed by oli-obk** 2019-06-26 09:09 UTC
Labels: A-style, L-lint
