### ISSUE TITLE
Detect when paths in `src/utils/path.rs` become outdated

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust-clippy#6274] opened 2020-10-31 01:57 UTC
Clippy lists a lot of different paths in https://github.com/rust-lang/rust-clippy/blob/084b203988e04bcf89d3b2d6bbc77b65ecfab553/clippy_lints/src/utils/paths.rs, which are represented as strings. If one of these becomes invalid due to a compiler refactoring, Clippy will continue to compile - however, the behavior of lints may change, since the path will never match anything.

It would be useful to validate that all of the paths are valid (if the crate at the beginning of the path is loaded). I'm not sure how difficult this would be - I think we would need access to the resolver before we run any lints.

I came across this in https://github.com/rust-lang/rust/pull/75534 - I moved the rustc `Lint` type, which caused an internal clippy lint to stop firing.

**Comment by ebroto** [comment] 2020-10-31 08:51
Duplicate of #6047

FYI #6244 partially addressed this, but the dogfood tests don't run in the rustc repo (I guess because it takes some time), so we need to find a way to check those paths, ideally without duplication.

**Closed by ebroto** 2020-10-31 08:51 UTC
Labels: L-bug
