### ISSUE TITLE
Clippy panic during --fix on latest Rust

### ISSUE THREAD

**Issue by sffc** [rust-lang/rust-clippy#8283] opened 2022-01-15 00:19 UTC
I get the following error when running `cargo clippy --fix` on Rust 1.58:

```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', compiler/rustc_query_impl/src/on_disk_cache.rs:500:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.58 (02072b4 2022-01-11)

query stack during panic:
#0 [predicates_of] computing predicates of `BmpBlockSelector`
#1 [param_env] computing normalized predicates of `BmpBlockSelector`
end of query stack
error: could not compile `icu_uniset`
```

Instructions to reproduce:

1. Check out https://github.com/unicode-org/icu4x/commit/61c588988256a9be8894714906dc4a89b69c39af
2. `cd utils/uniset`
3. `cargo clippy --fix`

**Comment by giraffate** [comment] 2022-01-16 12:48
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/8164, so I'm closing this.

**Closed by giraffate** 2022-01-16 12:48 UTC
