### ISSUE TITLE
error: multiple input filenames provided with clippy 0.0.191 and last nightly

### ISSUE THREAD

**Issue by mcilloni** [rust-lang/rust-clippy#2602] opened 2018-03-31 17:40 UTC
```
$ cargo new --lib lol
     Created library `lol` project
$ cd lol/
$ cargo clippy
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/marco/.cargo/bin/clippy-driver /usr/bin/rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 101)
--- stderr
error: multiple input filenames provided


$ rustc -V 
rustc 1.26.0-nightly (80785a547 2018-03-30)
$ cargo-clippy                                                                                                                                                                       
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/marco/.cargo/bin/clippy-driver /usr/bin/rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 101)
--- stderr
error: multiple input filenames provided


$ cargo-clippy -V                                                                                                                                                                     
0.0.191
```

Like in #2566, clippy is failing on my system with a "multiple input filenames" error. I cannot find any way to work around this, and invoking `cargo-clippy` directly leads to the same error.

**Comment by oli-obk** [comment] 2018-03-31 18:41
We have some weird code that checks the first argument and removes it if it is rustc, maybe we can now remove it unconditionally

**Comment by oli-obk** [comment] 2018-04-01 22:53
We have some weird code that checks the first argument and removes it if it is rustc, seems to not work for paths

**Comment by phansch** [comment] 2018-12-07 21:50
@mcilloni Is this still happening for you when using Clippy via Rustup?

**Comment by ThibsG** [comment] 2020-10-25 15:26
I think we can close this now, since we cannot reproduce this anymore.

**Closed** 2020-10-25 15:36 UTC
Labels: L-bug
