### ISSUE TITLE
Build fails after upgrade to version 1.51.0-nightly (b12290861 2021-01-29)

### ISSUE THREAD

**Issue by benjaminSchilling33** [rust-lang/rust-clippy#6652] opened 2021-01-30 13:49 UTC
I'm opening this issue since Cippy told be to do it.

I'm using Github actions to build my software.
In the pipeline I'm installing the latest rust nightly build.

Yesterday I was using `rust version 1.51.0-nightly (c0b64d97b 2021-01-28)` and today `rust version 1.51.0-nightly (b12290861 2021-01-29)` is installed.

Now the error below occurs during build. Please tell me if more log data is needed.

This is not only happening with clippy, also the "regular" builds fail.

```
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
  error: internal compiler error: unexpected panic
  
  note: the compiler unexpectedly panicked. this is a bug.
  
  note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new
  
  note: Clippy version: clippy 0.1.51 (b122908 2021-01-29)
  
  query stack during panic:
  end of query stack
  error: could not compile `mongodb`
  
  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  {"reason":"compiler-artifact","package_id":"openidconnect 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"crate_types":["lib"],"name":"openidconnect","src_path":"/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/openidconnect-1.1.1/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":["default","reqwest-09"],"filenames":["/home/runner/work/lol/lol/target/debug/deps/libopenidconnect-2c8898de9d635b37.rmeta"],"executable":null,"fresh":false}
  {"reason":"build-finished","success":false}
  error: build failed
Clippy results: 0 ICE, 0 errors, 0 warnings, 0 notes, 0 help
```

**Comment by phansch** [comment] 2021-01-31 11:12
Thanks for the report!

> This is not only happening with clippy, also the "regular" builds fail.

If that's the case, then this is not a Clippy issue but a Rustc issue. I will try and see if can reproduce it and find an existing issue over at https://github.com/rust-lang/rust.

**Comment by phansch** [comment] 2021-01-31 12:12
I'm able to reproduce this on [mongo-rust-driver](https://github.com/mongodb/mongo-rust-driver) with `v1.1.1` checked out and on the 2021-01-30 nightly:

```
git clone https://github.com/mongodb/mongo-rust-driver
cd mongo-rust-driver
git checkout v1.1.1
rustup override set nightly-2021-01-30
cargo clippy
```

Backtrace:

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
```

It looks like there's already an issue for this bug in rustc: https://github.com/rust-lang/rust/issues/81531
As well as an open PR: https://github.com/rust-lang/rust/pull/81541

Since this is not something that can or should be fixed in Clippy, I'm going to go ahead and close this issue. Thanks again for the report!

**Closed by phansch** 2021-01-31 12:12 UTC
Labels: L-bug, L-crash, P-high
