### ISSUE TITLE
Panic when running cargo clippy

### ISSUE THREAD

**Issue by bragaigor** [rust-lang/rust-clippy#8459] opened 2022-02-22 18:16 UTC
Received a Panic when running the following command:
```
cargo clippy --all-targets --all-features -- -D warnings
```
Cargo version:
```
cargo --version                                         
cargo 1.57.0 (b2e52d7ca 2021-10-21)
```

Rustc version:
```
rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

Error:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.57 (f1edd042 2021-11-29)

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `impl core::future::future::Future: core::marker::Send`
#1 [typeck] type-checking `streamer::get_and_process_messages`
end of query stack
```

**Comment by giraffate** [comment] 2022-02-24 00:46
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/8254, so I'm closing this.

**Closed by giraffate** 2022-02-24 00:46 UTC

**Comment by bragaigor** [comment] 2022-02-24 00:51
Ah I should have checked. It's my pleasure and thanks!
