### ISSUE TITLE
LateContext::typeck_results called outside of body

### ISSUE THREAD

**Issue by hrls** [rust-lang/rust-clippy#7467] opened 2021-07-15 07:41 UTC
Clippy version: clippy 0.1.55 (2f391da2 2021-07-14)

```
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

Stack backtrace:
```
thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
stack backtrace:
   0:        0x10f938604 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha608b2403413f2de
   1:        0x10f99d04c - core::fmt::write::h8160330c41daaf61
   2:        0x10f92a4ea - std::io::Write::write_fmt::hcc06e740c7b6e2d7
   3:        0x10f93c1cf - std::panicking::default_hook::{{closure}}::h928c39889e2b3d97
   4:        0x10f93bccd - std::panicking::default_hook::hf7460227d8d42fa9
   5:        0x10f1d20a8 - clippy_driver::ICE_HOOK::{{closure}}::{{closure}}::h366426257a7c5257
   6:        0x10f93ca26 - std::panicking::rust_panic_with_hook::h138fc405eedb575b
   7:        0x10f93c4a5 - std::panicking::begin_panic_handler::{{closure}}::hdfe025b2d4661d54
   8:        0x10f938a78 - std::sys_common::backtrace::__rust_end_short_backtrace::h4125d2df6fba2b43
   9:        0x10f93c40a - _rust_begin_unwind
  10:        0x10f9c946f - core::panicking::panic_fmt::h2e3306ce37bd7247
  11:        0x10f9c937a - core::option::expect_failed::h90af5e5135b5f0b7
  12:        0x119553d8e - rustc_lint::context::LateContext::typeck_results::h10d3373080f23d36
  13:        0x10f344629 - <clippy_lints::use_self::UseSelf as rustc_lint::passes::LateLintPass>::check_ty::hd7a34dce78e9eaae
  14:        0x1194f3553 - <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_ty::he3a8357cea1a853b
  15:        0x115a73908 - rustc_hir::intravisit::walk_item::h7a2e442e31b3b52e
  16:        0x115a7a4c2 - rustc_hir::intravisit::Visitor::visit_nested_item::h6be2ec4fef34d756
  17:        0x115a6a957 - rustc_hir::intravisit::walk_block::ha3e47980c05f340c
  18:        0x115a70ea2 - rustc_hir::intravisit::walk_expr::h2cb434e3891fd70a
  19:        0x115a6ff24 - rustc_hir::intravisit::walk_body::h86a66c63020cf222
  20:        0x115a796bc - <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body::hfbcc5f2786d76f64
  21:        0x115a7983d - <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn::h175eaf7bce4259ba
  22:        0x115a6ba17 - rustc_hir::intravisit::walk_impl_item::h2191e3452ba17ee3
  23:        0x115a7b2d8 - rustc_hir::intravisit::Visitor::visit_nested_impl_item::h6b6498c684f7b29e
  24:        0x115a6d8c4 - rustc_hir::intravisit::walk_impl_item_ref::h4176319fd60afce6
  25:        0x115a73edc - rustc_hir::intravisit::walk_item::h7a2e442e31b3b52e
  26:        0x115a7a4c2 - rustc_hir::intravisit::Visitor::visit_nested_item::h6be2ec4fef34d756
  27:        0x115a7385c - rustc_hir::intravisit::walk_item::h7a2e442e31b3b52e
  28:        0x115a7a4c2 - rustc_hir::intravisit::Visitor::visit_nested_item::h6be2ec4fef34d756
  29:        0x115a6ad7d - rustc_hir::intravisit::walk_crate::hc0fe7411405ad7a0
  30:        0x115a74e62 - rustc_lint::late::late_lint_pass_crate::hc3531f0e5930951f
  31:        0x115a743b0 - rustc_lint::late::late_lint_crate::hfd28627c4531610a
  32:        0x115a57c38 - rustc_session::utils::<impl rustc_session::session::Session>::time::h9acaf12e96013dbe
  33:        0x115a7dc95 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h41a68143b0f71265
  34:        0x115a57aab - rustc_session::utils::<impl rustc_session::session::Session>::time::h8a2fac002d910830
  35:        0x1159f4eb3 - rustc_interface::passes::analysis::hfc2bf492ff239304
  36:        0x118716823 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h259028e9c6973097
  37:        0x1188061a6 - rustc_data_structures::stack::ensure_sufficient_stack::ha10366b216dd4943
  38:        0x118506b7c - rustc_query_system::query::plumbing::force_query_with_job::hc9772a3b4d3d894a
  39:        0x11849cd5c - rustc_query_system::query::plumbing::get_query_impl::hbb0ff14117ee6200
  40:        0x1186423fa - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h81e1da614ce021ad
  41:        0x1159107c9 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hb49941e8d8589a92
  42:        0x1158d5c86 - rustc_span::with_source_map::hd53c358f8b297099
  43:        0x115911652 - rustc_interface::interface::create_compiler_and_run::h5a07f24028332910
  44:        0x1158ea20f - scoped_tls::ScopedKey<T>::set::h247ba0db7ba173ad
  45:        0x1158e36a9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h518f2d2f7ca453bb
  46:        0x1158d7cfd - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf1e4446d82c04b0e
  47:        0x10f947deb - std::sys::unix::thread::Thread::new::thread_start::h00ff94d277778eb5
  48:     0x7fff706d0109 - __pthread_start
```

**Comment by giraffate** [comment] 2021-07-15 08:11
Thanks for the report!

I'm closing this because it's duplicate of https://github.com/rust-lang/rust-clippy/issues/7423.

**Closed by giraffate** 2021-07-15 08:11 UTC
