### ISSUE TITLE
Improper warning about `useless_let_if_seq`

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust-clippy#4914] opened 2019-12-19 00:21 UTC
Hi, the following code:
```rust
        let mut changed = false;
        if self.transform_dirty.check() {
            ...
            changed = true;
        }
        if self.projection_dirty.check() {
            ...
            changed = true;
        }
        if changed {
            ...
        }
```
gives a warning:

```
help: it is more idiomatic to write: `let <mut> changed = if self.transform_dirty.check() { ..; true } else { false };`
```

Which I believe could not be applied here.

**Comment by mikerite** [comment] 2019-12-19 05:06
Duplicate of #3769

**Closed** 2019-12-21 15:26 UTC
