### ISSUE TITLE
`bool::then` -> `bool::then_some` within `unnecessary_lazy_eval` can suggest fixes that can panic

### ISSUE THREAD

**Issue by alokedesai** [rust-lang/rust-clippy#9814] opened 2022-11-07 23:40 UTC
### Summary

The `bool::then` -> `bool::then_some` suggestions for `unnecessary_lazy_eval` can be problematic if the underlying body of the closure is not actually trivial. See repro below for a concrete example.

This is especially problematic because `cargo clippy --fix` will auto-fix this, which can inadvertently cause a new panic.

### Lint Name

unnecessary_lazy_eval

### Reproducer

I tried this code:

```rust
let foo : usize = 0;
let option = (foo > 0).then_some(|| foo - 1)
```

I saw this happen:

```
warning: unnecessary closure used with `bool::then`
```
This is _incorrect_, since `bool:then` will panic in a case where `then_some` would not have.

I expected to see this happen:
No clippy warning suggested.

### Version

```text
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: aarch64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by kraktus** [comment] 2022-11-09 09:56
Hey, thanks for reporting.

This seem a duplicate of https://github.com/rust-lang/rust-clippy/issues/9422

**Comment by alokedesai** [comment] 2022-11-09 14:50
@kraktus Yes thats correct! Feel free to close to keep that as the canonical issue :) Would love a status on this--we basically have to allow the `unnecessary_lazy_evaluations` throughout our project because of the concern it could cause panics with an errant fix

**Closed** 2023-11-17 19:00 UTC
Labels: C-bug, I-false-positive
