### ISSUE TITLE
compiler unexpectedly panicked

### ISSUE THREAD

**Issue by Right2Left** [rust-lang/rust-clippy#5243] opened 2020-02-29 03:57 UTC
$ rustc -V
rustc 1.43.0-nightly (6d69caba1 2020-02-27)
$ cargo --version
cargo 1.43.0-nightly (e57bd0299 2020-02-21)
$ cargo clippy -V
clippy 0.0.212 (fc5d0cc5 2020-02-24)

error: internal compiler error: src\librustc_mir\dataflow\generic\engine.rs:315: Switch on discriminant of non-ADT

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:881:9
stack backtrace:
   0:     0x7ff897c8a0ff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf92e59afa881839c
   1:     0x7ff897cb7b5b - core::fmt::write::hda3bb8db568d2524
   2:     0x7ff897c7aa44 - <std::io::IoSlice as core::fmt::Debug>::fmt::he113711a38248335
   3:     0x7ff897c8f2bc - std::panicking::take_hook::he442b76a11eff395
   4:     0x7ff897c8ef0f - std::panicking::take_hook::he442b76a11eff395
   5:     0x7ff6bfd92ac4 - <unknown>
   6:     0x7ff897c8fac8 - std::panicking::rust_panic_with_hook::h950cdb0aa90e456e
   7:     0x7ff8779ec925 - <rustc_errors::json::Diagnostic::from_errors_diagnostic::BufWriter as std::io::Write>::flush::h0ac544c6aacabec0
   8:     0x7ff8779cbdef - rustc_errors::HandlerInner::treat_err_as_bug::hbcf694dcf8fe92a8
   9:     0x7ff8779ca822 - rustc_errors::Handler::bug::h3486ea2f4a7feadd
  10:     0x7ff87753ead2 - rustc::util::bug::bug_fmt::h442b593e91bfda34
  11:     0x7ff877539f10 - <rustc_attr::builtin::IntType as rustc::ty::util::IntTypeExt>::disr_incr::hee37cf6e2b90658f
  12:     0x7ff8775397b3 - <rustc_attr::builtin::IntType as rustc::ty::util::IntTypeExt>::disr_incr::hee37cf6e2b90658f
  13:     0x7ff87753e9df - rustc::util::bug::bug_fmt::h442b593e91bfda34
  14:     0x7ff87753e93d - rustc::util::bug::bug_fmt::h442b593e91bfda34
  15:     0x7ff6bfec13f6 - <unknown>
  16:     0x7ff6bff3bcbd - <unknown>
  17:     0x7ff876f6eada - <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn::h2ee3b7c3b2a361dd
  18:     0x7ff873ea0a0f - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  19:     0x7ff873ea5ceb - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  20:     0x7ff873ea067d - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  21:     0x7ff873ea57ff - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  22:     0x7ff873ea067d - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  23:     0x7ff873ea4324 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  24:     0x7ff873ea0a67 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  25:     0x7ff873ea246c - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  26:     0x7ff873ea1199 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  27:     0x7ff873ea7a9f - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  28:     0x7ff873ea1077 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  29:     0x7ff873ea728f - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  30:     0x7ff873ea1077 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  31:     0x7ff873ea728f - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  32:     0x7ff873ea1077 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  33:     0x7ff873ea728f - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  34:     0x7ff873ea1077 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  35:     0x7ff873ea15ae - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  36:     0x7ff873e988e1 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  37:     0x7ff873e97d27 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  38:     0x7ff873e05448 - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  39:     0x7ff873d8a239 - <<serde::de::impls::range::Field as serde::de::Deserialize>::deserialize::FieldVisitor as serde::de::Visitor>::expecting::hcf336536514bdb93
  40:     0x7ff897ca2792 - _rust_maybe_catch_panic
  41:     0x7ff873d8a00f - <<serde::de::impls::range::Field as serde::de::Deserialize>::deserialize::FieldVisitor as serde::de::Visitor>::expecting::hcf336536514bdb93
  42:     0x7ff897ca2792 - _rust_maybe_catch_panic
  43:     0x7ff873e0393c - rustc_interface::passes::BoxedResolver::complete::h67e75fc8f2db0bf7
  44:     0x7ff873dfd253 - rustc_interface::passes::QueryContext::print_stats::h78f99144a43fb4ce
  45:     0x7ff873c45735 - chalk_engine::TableIndex::increment::hcae568cf05580d01
  46:     0x7ff873ca7b7e - <alloc::vec::Vec<syntax::ast::Attribute> as syntax::attr::HasAttrs>::attrs::h2720906636c88cf0
  47:     0x7ff873c7cd69 - <alloc::vec::Vec<syntax::ast::Attribute> as syntax::attr::HasAttrs>::attrs::h2720906636c88cf0
  48:     0x7ff873cb56ee - <alloc::vec::Vec<syntax::ast::Attribute> as syntax::attr::HasAttrs>::attrs::h2720906636c88cf0
  49:     0x7ff873c88094 - <alloc::vec::Vec<syntax::ast::Attribute> as syntax::attr::HasAttrs>::attrs::h2720906636c88cf0
  50:     0x7ff873c40f46 - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h7f67a6cd1328973f
  51:     0x7ff897ca2792 - _rust_maybe_catch_panic
  52:     0x7ff873c8a612 - <alloc::vec::Vec<syntax::ast::Attribute> as syntax::attr::HasAttrs>::attrs::h2720906636c88cf0
  53:     0x7ff897c68487 - ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  54:     0x7ff897c9fbcc - std::sys::windows::thread::Thread::new::he3610643083a1753
  55:     0x7ff8d8177974 - BaseThreadInitThunk
  56:     0x7ff8dae1a271 - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (fc5d0cc5 2020-02-24)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

**Comment by JohnTitor** [comment] 2020-02-29 03:58
Duplicate of #5238

**Closed by JohnTitor** 2020-02-29 03:58 UTC
