### ISSUE TITLE
Internal Compiler Error: Switch on discriminant of non-ADT

### ISSUE THREAD

**Issue by lawliet89** [rust-lang/rust-clippy#5249] opened 2020-03-02 02:21 UTC
I was running Clippy on code in this specific [commit](https://github.com/basisai/vault-k8s-helper/tree/251e630d5f59841efd060e661d06c6cb294901c8) and I ran into the compiler error below:

```
    Checking vault-k8s-helper v0.3.0 (/home/yongwen/work/open/vault-gke-helper)
error: internal compiler error: src/librustc_mir/dataflow/generic/engine.rs:315: Switch on discriminant of non-ADT

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:881:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (fc5d0cc 2020-02-24)

error: aborting due to previous error

error: could not compile `vault-k8s-helper`.

To learn more, run the command again with --verbose.
```

`clippy 0.0.212 (fc5d0cc 2020-02-24)`

**Comment by JohnTitor** [comment] 2020-03-02 02:24
Duplicate of #5238 and it's already fixed in latest nightly rustc, closing.

**Closed by JohnTitor** 2020-03-02 02:24 UTC
