### ISSUE TITLE
Clippy hangs on `.unwrap().unwrap() as usize` on nightly

### ISSUE THREAD

**Issue by stevenengler** [rust-lang/rust-clippy#12506] opened 2024-03-18 22:04 UTC
### Summary

When running `cargo clippy` on a library with the following code using rust nightly, it hangs and never completes. The clippy process CPU usage is at 100% of a core while it's running.

If anyone has a better title, please update it since I'm not sure exactly what's causing the bug.

### Reproducer

```rust
fn _foo() -> usize {
    let bar: Result<Option<i64>, u32> = Ok(Some(10));
    bar.unwrap().unwrap() as usize
}
```

It hangs with the output:

```text
    Checking clippy-bug v0.1.0 (/tmp/clippy-bug)
    Building [                             ] 0/1: clippy-bug
```

(I've waited 5 minutes, so I'm assuming it would hang forever.)

### Version

```text
rustc 1.79.0-nightly (eb45c8444 2024-03-17)
binary: rustc
commit-hash: eb45c844407968ea54df0d9870ebce9e3235b706
commit-date: 2024-03-17
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

**Comment by Centri3** [comment] 2024-03-18 22:27
Can't reproduce this on beta (currently 1.77.0-beta.9. The only commit since then is https://github.com/rust-lang/rust-clippy/commit/fc8f6628ab945fc1b8586d6a83d78f247eaf512c

**Comment by stevenengler** [comment] 2024-03-18 22:31
> Can't reproduce this on beta (currently 1.77.0-beta.9. The only commit since then is [fc8f662](https://github.com/rust-lang/rust-clippy/commit/fc8f6628ab945fc1b8586d6a83d78f247eaf512c)
> 
> (This commit isn't in beta despite it being a few days ago, I think.)

This can also be seen on the rust playground, where clippy works when set to "beta" but not "nightly".

**Comment by Centri3** [comment] 2024-03-18 22:32
Oh yeah I know, this is an issue, I was saying that it's something new since beta (so that PR I think)

**Comment by y21** [comment] 2024-03-18 22:38
Looks like it gets stuck in this loop
https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/casts/cast_sign_loss.rs#L135 (#12126)

This should probably reassign `expr` to actually peel off the method calls and not get stuck on the same expr forever?

**Closed** 2024-03-22 13:27 UTC
Labels: C-bug

**Comment by stevenengler** [comment] 2024-03-22 21:07
Thanks!
