### ISSUE TITLE
Cargo clippy crash

### ISSUE THREAD

**Issue by Adanos020** [rust-lang/rust-clippy#7443] opened 2021-07-07 18:46 UTC
Clippy crashes on nightly in my project, I noticed it happening after pushing [this commit](https://github.com/SMW-Editor/smw-editor/commit/239332bad1a7c90a8225cd1669466f4374d053b7) when one of the lint checks in GitHub Actions failed.

I could also reproduce this crash locally with the latest nightly version, by calling `cargo +nightly clippy`.

Callstack:
```
thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/option.rs:1243:5
   3: rustc_lint::context::LateContext::typeck_results
   4: <clippy_lints::use_self::UseSelf as rustc_lint::passes::LateLintPass>::check_ty
   5: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_ty
   6: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_ty
   7: rustc_hir::intravisit::walk_fn_decl
   8: rustc_hir::intravisit::walk_item
   9: rustc_hir::intravisit::Visitor::visit_nested_item
  10: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  11: rustc_hir::intravisit::walk_block
  12: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  13: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  14: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  15: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  16: rustc_hir::intravisit::walk_impl_item
  17: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  18: rustc_hir::intravisit::walk_impl_item_ref
  19: rustc_hir::intravisit::walk_item
  20: rustc_hir::intravisit::Visitor::visit_nested_item
  21: rustc_hir::intravisit::walk_mod
  22: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  23: rustc_hir::intravisit::Visitor::visit_nested_item
  24: rustc_hir::intravisit::walk_mod
  25: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  26: rustc_hir::intravisit::Visitor::visit_nested_item
  27: rustc_hir::intravisit::walk_mod
  28: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
  29: rustc_hir::intravisit::walk_crate
  30: rustc_lint::late::late_lint_pass_crate
  31: rustc_lint::late::late_lint_crate
  32: rustc_session::utils::<impl rustc_session::session::Session>::time
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  34: rustc_session::utils::<impl rustc_session::session::Session>::time
  35: rustc_interface::passes::analysis
  36: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  37: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  39: rustc_data_structures::stack::ensure_sufficient_stack
  40: rustc_query_system::query::plumbing::force_query_with_job
  41: rustc_query_system::query::plumbing::get_query_impl
  42: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  43: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  44: rustc_span::with_source_map
  45: rustc_interface::interface::create_compiler_and_run
  46: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.55 (8853999 2021-07-06)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `smwe_rom`
```

**Comment by giraffate** [comment] 2021-07-08 00:21
Thanks for the report!

This is duplicate of https://github.com/rust-lang/rust-clippy/issues/7423, so I'm closing this.

**Closed by giraffate** 2021-07-08 00:21 UTC
