### ISSUE TITLE
`too_long_first_doc_comment` adds outer-comment lines to inner-comments

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#13447] opened 2024-09-24 08:26 UTC
### Summary

The auto-fix for this lint will add `///` as the new line to `//!` comments, meaning it will break and cause a syntax error.

### Reproducer

```rust
#![warn(clippy::too_long_first_doc_comment)]
//! This is a one-line summary.
//! This makes the one-line summary no longer one line.
```

autofixes to:

```rust
#![warn(clippy::too_long_first_doc_comment)]
//! This is a one-line summary.
///
//! This makes the one-line summary no longer one line.
```

### Version

rustc 1.83.0-nightly (7042c269c 2024-09-23)
binary: rustc
commit-hash: 7042c269c166191cd5d8daf0409890903df7af57
commit-date: 2024-09-23
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0

### Additional Labels

@rustbot label +I-suggestion-causes-error

**Comment by y21** [comment] 2024-09-24 08:29
This looks like a duplicate of #13309 and was already fixed in #13377. It should be fixed in nightly when the next sync happens

**Closed** 2024-09-24 08:30 UTC
Labels: C-bug, I-suggestion-causes-error
