### ISSUE TITLE
Check usages of undefined features

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust-clippy#8301] opened 2022-01-17 07:11 UTC
### What it does

Warn usages of features that are not defined in `features` section of `Cargo.toml` and are not optional dependencies.

### Lint Name

undefined-features

### Category

correctness, suspicious

### Advantage

- Check misspelled feature names.
- Check unused code.

### Example

```rust
fn foo() {}

#[cfg(feature = "bar")]
fn bar() {}
```

If feature `"bar"` is not defined in `Cargo.toml`, the code above could be written as:

```rust
fn foo() {}
```

**Comment by jplatte** [comment] 2022-02-08 11:01
Duplicate of #1614.

**Comment by epage** [comment] 2024-03-04 19:25
Looks like there is also #11649 for this.  There is also native support coming to rustc/cargo, see https://github.com/rust-lang/rust/issues/82450

**Comment by Alexendoo** [comment] 2024-04-05 11:34
Closing in favour of https://github.com/rust-lang/rust/issues/82450

**Closed by Alexendoo** 2024-04-05 11:34 UTC
Labels: A-lint
