### ISSUE TITLE
Nightly clippy hangs on nalgebra crate

### ISSUE THREAD

**Issue by AnonymousAcid7787** [rust-lang/rust-clippy#13373] opened 2024-09-09 05:22 UTC
### Summary

I was a little skeptical of making an issue on a specific crate, but I believe that other crates that are similar to nalgebra might be impacted by this. When running nightly clippy on a crate that uses the nalgebra crate (version 0.33.0), clippy hangs on the nalgebra crate and never finishes checking it. As of right now, I have only tested this on a machine running Windows 10 with the latest version of nightly clippy.<br/>
Things that I have tried and their outcomes:
- run stable clippy (nothing went wrong)
- run nightly clippy on the nalgebra crate repo (clippy hanged at nalgebra here as well)
- run stable clippy on the nalgebra crate repo (clippy worked, but there were a lot of warnings)

### Reproducer

Steps to reproduce:
1. run `cargo init` in an empty folder
2. run `cargo add nalgebra`
3. run `rustup run nightly cargo clippy`

I expected to see this happen:
Clippy finishes running in a reasonable amount of time (~13s with stable clippy on my machine).
Instead, this happened:
Clippy stayed stuck on checking nalgebra and never finished. I waited for over an hour and it never finished.

### Version

```text
rustc 1.83.0-nightly (12b26c13f 2024-09-07)
binary: rustc
commit-hash: 12b26c13fba25c9e1bc2fdf05f3c2dbb851c83de
commit-date: 2024-09-07
host: x86_64-pc-windows-msvc
release: 1.83.0-nightly
LLVM version: 19.1.0
```

**Comment by smoelius** [comment] 2024-09-09 09:35
The hang is reproducible with `cargo +nightly check`, so I think the problem is in the compiler itself.

In a stack trace, these two functions appear repeatedly:
```
#1  0x00007ffff....... in <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::generic_args::GenericArg> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_next_trait_solver::canonicalizer::Canonicalizer<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>> ()
   from $HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-67e992fc9ebdf5ae.so
#2  0x00007ffff....... in <rustc_next_trait_solver::canonicalizer::Canonicalizer<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt> as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_ty () from $HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-67e992fc9ebdf5ae.so
```
With the Clippy in master (0ee2650e07ccd0b87d945d38e52c84b4dbc752c8), there is a noticeable delay of about 10 seconds, but Clippy does eventually finish.

(Sorry, I didn't debug further.)

**Comment by smoelius** [comment] 2024-09-09 09:40
Just happened upon this by coincidence: https://github.com/rust-lang/rust/issues/130056

**Comment by Jarcho** [comment] 2024-09-11 19:04
Closing as this is a rustc issue.

**Closed by Jarcho** 2024-09-11 19:04 UTC
Labels: C-bug
