### ISSUE TITLE
Index out of bounds when building mir

### ISSUE THREAD

**Issue by kod-kristoff** [rust-lang/rust-clippy#8129] opened 2021-12-15 16:24 UTC
When running cargo clippy on kod-kristoff/json-streams-rs
on Termux (Android 7) rust version 1.56.1
```
thread 'rustc' panicked at 'index out of bounds: the len is 14 but the index is 37', compiler/rustc_mir_build/src/build/cfg.rs:13:14          
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                        error: internal compiler error: unexpected panic                                                                                              
note: the compiler unexpectedly panicked. this is a bug.                                                                                      
note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new                                                                                                                          
note: Clippy version: clippy 0.1.56                                                                                                           
query stack during panic:                                              
#0 [mir_built] building MIR for `json_iter::load_from_read`            
#1 [unsafety_check_result] unsafety-checking `json_iter::load_from_read`                                                                      
end of query stack
```

**Comment by kod-kristoff** [comment] 2021-12-15 17:32
And with rust 1.57.0 and Clippy 0.1.57
```
thread 'rustc' panicked at 'index out of bounds: the len is 13 but the index is 39', compiler/rustc_mir_build/src/build/cfg.rs:13:14          
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                        
error: internal compiler error: unexpected panic                                                                                              
note: the compiler unexpectedly panicked. this is a bug.                                                                                      
note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new                                                                                                                          
note: Clippy version: clippy 0.1.57                                                                                                           
query stack during panic:                                              
#0 [mir_built] building MIR for `json_iter::load_from_read`            
#1 [unsafety_check_result] unsafety-checking `json_iter::load_from_read`                                                                      
end of query stack

thread 'rustc' panicked at 'index out of bounds: the len is 13 but the index is 57', compiler/rustc_mir_build/src/build/cfg.rs:13:14                                                                                 
error: internal compiler error: unexpected panic                                                                                              
note: the compiler unexpectedly panicked. this is a bug.                                                                                      
note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new                                                                                                                          
note: Clippy version: clippy 0.1.57                                                                                                           
query stack during panic:                                              
#0 [mir_built] building MIR for `json_iter::<impl at src/json_iter.rs:46:1: 72:2>::next`                                                      
#1 [unsafety_check_result] unsafety-checking `json_iter::<impl at src/json_iter.rs:46:1: 72:2>::next`                                         
end of query stack                                                                   
warning: `json-streams` (lib) generated 3 warnings                     
error: could not compile `json-streams`; 3 warnings emitted                                                                                   json-streams-rs on  main is 📦 v0.0.1 via 🦀 v1.57.0 took 1m34s                                                 ❯
```

**Comment by giraffate** [comment] 2021-12-16 00:51
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/7952, so I'm closing this.

**Closed by giraffate** 2021-12-16 00:51 UTC
