### ISSUE TITLE
Disable `empty_enum` lint on stable (or change recommendation)

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust-clippy#6422] opened 2020-12-04 23:26 UTC
Currently the [`empty_enum` lint](https://rust-lang.github.io/rust-clippy/master/index.html#empty_enum) recommends using the seemingly forever-unstable never type. While the never type may have better compiler support _in some aspects_, the suggested change to use a wrapper type around `!` obviously isn't possible on stable.

I'm not sure whether clippy currently has the ability to have nightly-only lints, but it's what makes sense here imo.

**Comment by nahuakang** [comment] 2020-12-25 10:02
Has anyone worked on this? If not, I'd be happy to jump on it. @flip1995 Might need a few hints :)

**Comment by flip1995** [comment] 2020-12-27 13:38
@nahuakang You can check with
https://github.com/rust-lang/rust-clippy/blob/abce9e7c9fc0520da4556ca641cce9aee462c2fc/clippy_lints/src/unnested_or_patterns.rs#L75-L78

if a specific feature is enabled. This lint should only trigger if the `never_type` feature is enabled.

**Comment by xFrednet** [comment] 2021-02-04 19:16
Hey, what is the status on this issue? It seems like #6513 implemented this. Can this one be closed or is there still something left to do? 🙃

**Comment by nahuakang** [comment] 2021-02-04 22:04
Hey Fred! @flip1995 can correct me if wrong, but I think the issue is fixed now :)

**Closed** 2021-02-04 22:13 UTC
Labels: L-enhancement, good-first-issue
