### ISSUE TITLE
Lint suggestion: undeclared_feature

### ISSUE THREAD

**Issue by pscott** [rust-lang/rust-clippy#5660] opened 2020-05-28 19:47 UTC
Hi,

This issue suggests a new lint: `undeclared_feature`. I tried following the guidelines, but feel free to change the name obviously.

Take a fresh `Cargo.toml` file and add time as an optional dependency. Now write this code:
```rust
#[cfg(feature=time)]
fn main() {
  println!("foo");
}

#[cfg(not(feature=time))]
fn main() {
  println!("bar");
}
```

You can then run:
```sh
$ cargo run
bar
```
and
```sh
$ cargo run --features time
foo
```

I _believe_ this is bad practice because this code effectively has a "hidden" feature, which should probably be documented and exposed via the Cargo.toml file. What do you think? Is this good / bad practice, and would a clippy lint be appropriate?

**Comment by pscott** [comment] 2020-05-28 19:50
I would ideally like to submit a PR for this issue. I'm working on it right now, but it's taking some time and I'm not too sure how to go about it, since I need to capture the `feature` used inside the code, and check it against a feature that would be declared inside the `Cargo.toml` file.

If someone here has a good idea on how I should go about doing that, please let me know. I've read the CONTRIBUTING.md and adding_lints.md, but I still have A LOT to learn ^^'

**Comment by flip1995** [comment] 2020-05-29 07:14
You can look at this PR, which implements pretty much, what you're asking for: #5643

Sadly, it is not clear, how to proceed with pre-expansion lints (which means, before code get's removed due to features).

**Comment by flip1995** [comment] 2020-05-29 07:19
Duplicate of https://github.com/rust-lang/rust-clippy/issues/1614

**Closed by flip1995** 2020-05-29 07:19 UTC

**Comment by flip1995** [comment] 2020-05-29 07:22
Thanks for wanting to contribute though! I just don't want to let your work go to waste. If you want to get familiar with hacking on Clippy, you can look at the [good first issues](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or if you want to add a new lint, you can look at the [`L-lint`](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+label%3AL-lint) label.

**Comment by pscott** [comment] 2020-05-29 08:36
> Thanks for wanting to contribute though! I just don't want to let your work go to waste. If you want to get familiar with hacking on Clippy, you can look at the [good first issues](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or if you want to add a new lint, you can look at the [`L-lint`](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+label%3AL-lint) label.

Yup, all good! I had try to look up in the issues but didn't find what I was looking for. In the meantime, I'm going to write a small program that does just that :) Thanks again!
