### ISSUE TITLE
Needs an Easter egg that makes a paperclip give you your lint messages.

### ISSUE THREAD

**Issue by icefoxen** [rust-lang/rust-clippy#3181] opened 2018-09-13 23:50 UTC
If Ansible can do it with cowsay, why can't we?

Willing to create a PR if nobody objects.

**Comment by mikerite** [comment] 2018-09-14 03:58
Duplicate of #2454

**Comment by icefoxen** [comment] 2018-09-14 05:08
Never have I been so happy to find that an issue I opened was a duplicate.

**Comment by phansch** [comment] 2018-12-11 18:22
Closing as duplicate (we should really implement the easter egg mode, though :rabbit: )

**Closed by phansch** 2018-12-11 18:22 UTC
