### ISSUE TITLE
decimal constant error

### ISSUE THREAD

**Issue by fabricedesre** [rust-lang/rust-clippy#1274] opened 2016-10-11 21:18 UTC
It looks like clippy is being confused by decimal in r# strings part of a macro:

error: this is a decimal constant
   --> components/core/src/utils.rs:128:55
    |
128 |             assert_eq!(json!([1, 100, 1000]), r#"[1,100,1000]"#);
    |                                                       ^
    |
note: lint level defined here
   --> components/core/src/lib.rs:10:9
    |
10  | #![deny(clippy)]
    |         ^^^^^^
help: if you mean to use a decimal constant, remove the `0` to remove confusion:
    |             assert_eq!(json!([1, 100, 1000]), r#"[1,10,1000]"#);
help: if you mean to use an octal constant, use `0o`:
    |             assert_eq!(json!([1, 100, 1000]), r#"[1,100o,1000]"#);
    = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#zero_prefixed_literal

error: aborting due to previous error

error: Could not compile `foxbox_core`.

**Comment by mcarton** [comment] 2016-10-11 21:27
That's a weird one :confused:
That lint only checks for `LitKind::Int`.
I can't reproduce it, can you reduce it to a self-contained example?

**Comment by mcarton** [comment] 2016-10-11 21:45
Oh I know, the problem is from `json!` but at no point we ever check for macros in that lint and we look at snippets.
@fabricedesre what crate does `json!` come from?

**Comment by fabricedesre** [comment] 2016-10-11 21:47
It's not from a published crate, but from: https://github.com/fxbox/foxbox/blob/master/components/core/src/utils.rs#L18

**Comment by phansch** [comment] 2020-12-18 16:13
Going to close this issue as the lint doesn't trigger anymore these days: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=458c92788f0b6472ea3f6f6bf910b3a2

**Closed by phansch** 2020-12-18 16:13 UTC
Labels: L-bug
