### ISSUE TITLE
Suggest `format!("{x}")` syntax when possible

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust-clippy#8675] opened 2022-04-10 11:24 UTC
### What it does

Given a use of a format macro, suggest to use the [`format!("{x}")` syntax](https://github.com/rust-lang/rust/pull/90473/) when applicable.

### Lint Name

format_args_capture

### Category

pedantic

### Advantage

* Code is shorter and more readable
* Increases awareness of the new syntax

### Drawbacks

* Increases MSRV for projects that care about that

### Example

```rust
let x = 2;
println!("{}", x);
println!("{x}", x = x);
println!("{y}", y = x); // untouched because variable name doesn't match
```

Could be written as:

```rust
let x = 2;
println!("{x}");
println!("{x}");
println!("{y}", y = x); // untouched because variable name doesn't match
```

**Comment by jplatte** [comment] 2022-04-12 14:33
Duplicate of #8368.

**Comment by giraffate** [comment] 2022-04-13 00:44
Thanks for suggesting a new lint!

I'm closing this because of https://github.com/rust-lang/rust-clippy/issues/8675#issuecomment-1096810164.

**Closed by giraffate** 2022-04-13 00:44 UTC
Labels: A-lint
