### ISSUE TITLE
ICE: panicked at 'index out of bounds: the len is 453 but the index is 480'

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust-clippy#8255] opened 2022-01-09 21:36 UTC
### Summary

Encountered this bug while working on https://github.com/paritytech/wasmi/pull/318.

This is the `clippy` output:
```
    Checking wasmi v0.11.0 (/home/home/projects/wasmi)
thread 'rustc' panicked at 'index out of bounds: the len is 453 but the index is 480', compiler/rustc_query_impl/src/on_disk_cache.rs:712:18
stack backtrace:
   0:     0x7fdbd77ad19c - std::backtrace_rs::backtrace::libunwind::trace::h4584385f29b6f33b
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fdbd77ad19c - std::backtrace_rs::backtrace::trace_unsynchronized::h330a1e343578c251
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdbd77ad19c - std::sys_common::backtrace::_print_fmt::hddeb4e39cc28a976
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fdbd77ad19c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha40aa4084225d251
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fdbd780cddc - core::fmt::write::h024ad879928ac02b
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/core/src/fmt/mod.rs:1149:17
   5:     0x7fdbd779cc75 - std::io::Write::write_fmt::h4ecd951415e658be
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/io/mod.rs:1660:15
   6:     0x7fdbd77b1460 - std::sys_common::backtrace::_print::hd38b4cedcf9f7c2b
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fdbd77b1460 - std::sys_common::backtrace::print::h0639ea13887de2fa
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fdbd77b1460 - std::panicking::default_hook::{{closure}}::h15662faef2c7d7c0
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/panicking.rs:211:50
   9:     0x7fdbd77b1019 - std::panicking::default_hook::h1f71caff0c379bff
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/panicking.rs:228:9
  10:     0x5651dbb1dce1 - clippy_driver[5f9c6b2e04db3198]::ICE_HOOK::{closure#0}::{closure#0}
  11:     0x7fdbd77b1bfb - std::panicking::rust_panic_with_hook::hb74a7fdbae1974db
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/panicking.rs:610:17
  12:     0x7fdbd77b1930 - std::panicking::begin_panic_handler::{{closure}}::h08face88258a528c
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/panicking.rs:502:13
  13:     0x7fdbd77ad634 - std::sys_common::backtrace::__rust_end_short_backtrace::h6a0c28dcc589eef2
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x7fdbd77b1699 - rust_begin_unwind
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/panicking.rs:498:5
  15:     0x7fdbd7778da1 - core::panicking::panic_fmt::h5c65784b908f9a58
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/core/src/panicking.rs:107:14
  16:     0x7fdbd7778d62 - core::panicking::panic_bounds_check::h652e39a18ad6bbd0
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/core/src/panicking.rs:75:5
  17:     0x7fdbd98cd2aa - <rustc_span[9f3485c9addfbc90]::span_encoding::Span as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  18:     0x7fdbd98ca310 - <rustc_middle[94f47f396b7f3eec]::ty::VariantDef as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  19:     0x7fdbd988ddc7 - <rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder as rustc_serialize[21f6589c366e8169]::serialize::Decoder>::read_seq::<alloc[89551571ceeb6bb2]::vec::Vec<rustc_middle[94f47f396b7f3eec]::ty::VariantDef>, <alloc[89551571ceeb6bb2]::vec::Vec<rustc_middle[94f47f396b7f3eec]::ty::VariantDef> as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode::{closure#0}>
  20:     0x7fdbda30bec7 - <rustc_middle[94f47f396b7f3eec]::ty::adt::AdtDef as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  21:     0x7fdbd987276e - <rustc_middle[94f47f396b7f3eec]::ty::sty::TyKind as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  22:     0x7fdbd98c27f0 - <&rustc_middle[94f47f396b7f3eec]::ty::TyS as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  23:     0x7fdbd98728b4 - <rustc_middle[94f47f396b7f3eec]::ty::sty::TyKind as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  24:     0x7fdbd98c27f0 - <&rustc_middle[94f47f396b7f3eec]::ty::TyS as rustc_serialize[21f6589c366e8169]::serialize::Decodable<rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7fdbda3355e9 - <rustc_query_impl[ca1d3d04651f511f]::on_disk_cache::OnDiskCache>::try_load_query_result::<&rustc_middle[94f47f396b7f3eec]::ty::TyS>
  26:     0x7fdbd98126c5 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_span[9f3485c9addfbc90]::def_id::DefId, &rustc_middle[94f47f396b7f3eec]::ty::TyS>
  27:     0x7fdbd985d8d8 - <rustc_query_impl[ca1d3d04651f511f]::Queries as rustc_middle[94f47f396b7f3eec]::ty::query::QueryEngine>::type_of
  28:     0x7fdbd9433360 - <rustc_typeck[143f2b449ec1a24b]::outlives::implicit_infer::InferVisitor as rustc_hir[1976edf0f8dc873e]::itemlikevisit::ItemLikeVisitor>::visit_item
  29:     0x7fdbd940aecb - <rustc_middle[94f47f396b7f3eec]::hir::map::Map>::visit_all_item_likes::<rustc_typeck[143f2b449ec1a24b]::outlives::implicit_infer::InferVisitor>
  30:     0x7fdbda07ce17 - rustc_typeck[143f2b449ec1a24b]::outlives::inferred_outlives_crate
  31:     0x7fdbd88a7160 - <rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind as rustc_query_system[cef9252f1c0eab16]::dep_graph::DepKind>::with_deps::<<rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[94f47f396b7f3eec]::ty::context::TyCtxt, (), rustc_middle[94f47f396b7f3eec]::ty::CratePredicatesMap>::{closure#0}, rustc_middle[94f47f396b7f3eec]::ty::CratePredicatesMap>
  32:     0x7fdbd897d373 - <rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[94f47f396b7f3eec]::ty::context::TyCtxt, (), rustc_middle[94f47f396b7f3eec]::ty::CratePredicatesMap>
  33:     0x7fdbd888f35c - rustc_data_structures[7ac4275ff06e9c83]::stack::ensure_sufficient_stack::<(rustc_middle[94f47f396b7f3eec]::ty::CratePredicatesMap, rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepNodeIndex), rustc_query_system[cef9252f1c0eab16]::query::plumbing::execute_job<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, (), rustc_middle[94f47f396b7f3eec]::ty::CratePredicatesMap>::{closure#3}>
  34:     0x7fdbda228e1a - rustc_query_system[cef9252f1c0eab16]::query::plumbing::try_execute_query::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_query_system[cef9252f1c0eab16]::query::caches::ArenaCache<(), rustc_middle[94f47f396b7f3eec]::ty::CratePredicatesMap>>
  35:     0x7fdbda2adc58 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::get_query::<rustc_query_impl[ca1d3d04651f511f]::queries::inferred_outlives_crate, rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt>
  36:     0x7fdbd9415774 - rustc_typeck[143f2b449ec1a24b]::outlives::inferred_outlives_of
  37:     0x7fdbda3719d7 - <rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[94f47f396b7f3eec]::ty::context::TyCtxt, rustc_span[9f3485c9addfbc90]::def_id::DefId, &[(rustc_middle[94f47f396b7f3eec]::ty::Predicate, rustc_span[9f3485c9addfbc90]::span_encoding::Span)]>
  38:     0x7fdbda2e18ae - rustc_data_structures[7ac4275ff06e9c83]::stack::ensure_sufficient_stack::<(&[(rustc_middle[94f47f396b7f3eec]::ty::Predicate, rustc_span[9f3485c9addfbc90]::span_encoding::Span)], rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepNodeIndex), rustc_query_system[cef9252f1c0eab16]::query::plumbing::execute_job<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_span[9f3485c9addfbc90]::def_id::DefId, &[(rustc_middle[94f47f396b7f3eec]::ty::Predicate, rustc_span[9f3485c9addfbc90]::span_encoding::Span)]>::{closure#3}>
  39:     0x7fdbda248682 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::try_execute_query::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_query_system[cef9252f1c0eab16]::query::caches::DefaultCache<rustc_span[9f3485c9addfbc90]::def_id::DefId, &[(rustc_middle[94f47f396b7f3eec]::ty::Predicate, rustc_span[9f3485c9addfbc90]::span_encoding::Span)]>>
  40:     0x7fdbda2bc091 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::force_query::<rustc_query_impl[ca1d3d04651f511f]::queries::inferred_outlives_of, rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt>
  41:     0x7fdbda31e7e6 - rustc_query_impl[ca1d3d04651f511f]::query_callbacks::inferred_outlives_of::force_from_dep_node
  42:     0x7fdbda600501 - <rustc_middle[94f47f396b7f3eec]::ty::context::TyCtxt as rustc_query_system[cef9252f1c0eab16]::dep_graph::DepContext>::try_force_from_dep_node
  43:     0x7fdbd98a2e4c - <rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt>
  44:     0x7fdbd98a25d6 - <rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt>
  45:     0x7fdbd9812ea5 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::ensure_must_run::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_span[9f3485c9addfbc90]::def_id::DefId, rustc_middle[94f47f396b7f3eec]::ty::generics::Generics>
  46:     0x7fdbd985fe4d - <rustc_query_impl[ca1d3d04651f511f]::Queries as rustc_middle[94f47f396b7f3eec]::ty::query::QueryEngine>::predicates_of
  47:     0x7fdbd9375b66 - <rustc_typeck[143f2b449ec1a24b]::collect::CollectItemTypesVisitor as rustc_hir[1976edf0f8dc873e]::intravisit::Visitor>::visit_item
  48:     0x7fdbd940bbe9 - <rustc_middle[94f47f396b7f3eec]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir[1976edf0f8dc873e]::intravisit::DeepVisitor<rustc_typeck[143f2b449ec1a24b]::collect::CollectItemTypesVisitor>>
  49:     0x7fdbda0182f2 - rustc_typeck[143f2b449ec1a24b]::collect::collect_mod_item_types
  50:     0x7fdbda3619b2 - <rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[94f47f396b7f3eec]::ty::context::TyCtxt, rustc_span[9f3485c9addfbc90]::def_id::LocalDefId, ()>
  51:     0x7fdbda2e2c0d - rustc_data_structures[7ac4275ff06e9c83]::stack::ensure_sufficient_stack::<((), rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepNodeIndex), rustc_query_system[cef9252f1c0eab16]::query::plumbing::execute_job<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_span[9f3485c9addfbc90]::def_id::LocalDefId, ()>::{closure#3}>
  52:     0x7fdbd97f77ae - rustc_query_system[cef9252f1c0eab16]::query::plumbing::try_execute_query::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_query_system[cef9252f1c0eab16]::query::caches::DefaultCache<rustc_span[9f3485c9addfbc90]::def_id::LocalDefId, ()>>
  53:     0x7fdbda2aabb3 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::get_query::<rustc_query_impl[ca1d3d04651f511f]::queries::collect_mod_item_types, rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt>
  54:     0x7fdbda076731 - <rustc_middle[94f47f396b7f3eec]::hir::map::Map>::for_each_module::<rustc_typeck[143f2b449ec1a24b]::check_crate::{closure#0}::{closure#0}::{closure#0}>
  55:     0x7fdbda0341aa - <rustc_session[a7bc60ac13078530]::session::Session>::track_errors::<rustc_typeck[143f2b449ec1a24b]::check_crate::{closure#0}, ()>
  56:     0x7fdbda01e6ad - rustc_typeck[143f2b449ec1a24b]::check_crate
  57:     0x7fdbd9db5587 - rustc_interface[a8648a120342801a]::passes::analysis
  58:     0x7fdbda37d300 - <rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepGraph<rustc_middle[94f47f396b7f3eec]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[94f47f396b7f3eec]::ty::context::TyCtxt, (), core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>
  59:     0x7fdbda2db673 - rustc_data_structures[7ac4275ff06e9c83]::stack::ensure_sufficient_stack::<(core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>, rustc_query_system[cef9252f1c0eab16]::dep_graph::graph::DepNodeIndex), rustc_query_system[cef9252f1c0eab16]::query::plumbing::execute_job<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, (), core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>::{closure#3}>
  60:     0x7fdbda2600d6 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::try_execute_query::<rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt, rustc_query_system[cef9252f1c0eab16]::query::caches::DefaultCache<(), core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>>
  61:     0x7fdbda2b5e25 - rustc_query_system[cef9252f1c0eab16]::query::plumbing::get_query::<rustc_query_impl[ca1d3d04651f511f]::queries::analysis, rustc_query_impl[ca1d3d04651f511f]::plumbing::QueryCtxt>
  62:     0x7fdbd9dab949 - <rustc_interface[a8648a120342801a]::passes::QueryContext>::enter::<rustc_driver[260b6e2c4087706]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>
  63:     0x7fdbd9daa1da - <rustc_interface[a8648a120342801a]::interface::Compiler>::enter::<rustc_driver[260b6e2c4087706]::run_compiler::{closure#1}::{closure#2}, core[512a5b486da53a1b]::result::Result<core[512a5b486da53a1b]::option::Option<rustc_interface[a8648a120342801a]::queries::Linker>, rustc_errors[fe6486514ed15b97]::ErrorReported>>
  64:     0x7fdbd9d893fd - rustc_span[9f3485c9addfbc90]::with_source_map::<core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>, rustc_interface[a8648a120342801a]::interface::create_compiler_and_run<core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>, rustc_driver[260b6e2c4087706]::run_compiler::{closure#1}>::{closure#1}>
  65:     0x7fdbd9da9b8a - rustc_interface[a8648a120342801a]::interface::create_compiler_and_run::<core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>, rustc_driver[260b6e2c4087706]::run_compiler::{closure#1}>
  66:     0x7fdbd9d8d1e2 - std[b426922cde994858]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a8648a120342801a]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[a8648a120342801a]::interface::run_compiler<core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>, rustc_driver[260b6e2c4087706]::run_compiler::{closure#1}>::{closure#0}, core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>::{closure#0}, core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>
  67:     0x7fdbd9dadfc2 - <<std[b426922cde994858]::thread::Builder>::spawn_unchecked<rustc_interface[a8648a120342801a]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[a8648a120342801a]::interface::run_compiler<core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>, rustc_driver[260b6e2c4087706]::run_compiler::{closure#1}>::{closure#0}, core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>::{closure#0}, core[512a5b486da53a1b]::result::Result<(), rustc_errors[fe6486514ed15b97]::ErrorReported>>::{closure#1} as core[512a5b486da53a1b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  68:     0x7fdbd77bcdc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb1776f60e0eddb20
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/alloc/src/boxed.rs:1811:9
  69:     0x7fdbd77bcdc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd270a7be29e70030
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/alloc/src/boxed.rs:1811:9
  70:     0x7fdbd77bcdc3 - std::sys::unix::thread::Thread::new::thread_start::h157b02f17d56a408
                               at /rustc/78fd0f633faaa5b6dd254fc1456735f63a1b1238/library/std/src/sys/unix/thread.rs:108:17
  71:     0x7fdbd76b4259 - start_thread
  72:     0x7fdbd74975e3 - __GI___clone
  73:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.59 (78fd0f6 2021-12-29)

query stack during panic:
#0 [type_of] computing type of `module::NotStartedModuleRef::loaded_module`
#1 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
#2 [inferred_outlives_of] computing inferred outlives predicates of `Error`
#3 [collect_mod_item_types] collecting item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `wasmi`
```

### Reproducer

Check out the PR at https://github.com/paritytech/wasmi/pull/318 and use `cargo clippy`.
Apparently performing `cargo clean` "fixed" the problem for me ... so might be that this is not reproducible.

### Version

```text
`rustup show` shows:


Default host: x86_64-unknown-linux-gnu
rustup home:  /home/robrob/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2021-10-19-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.59.0-nightly (78fd0f633 2021-12-29)
```
```


### Additional Labels

_No response_

**Comment by matthiaskrgr** [comment] 2022-01-09 22:15
Probably a rustc incremental compilation issue
https://github.com/rust-lang/rust/issues?q=is%3Aissue+compiler%2Frustc_query_impl%2Fsrc%2Fon_disk_cache.rs

**Comment by xFrednet** [comment] 2024-07-17 21:09
Triage here, this ICE is currently not reproducible. Clippy doesn't ICE on v0.35.0 from crates.io.

As @matthiaskrgr suggested, it's likely that this is/was a caching issue from rustc. Since `cargo clean` fixed it, I would close this issue. If this comes up again, you're please open another issue.

**Closed by xFrednet** 2024-07-17 21:09 UTC
Labels: I-ICE
