### ISSUE TITLE
format!("{}", X) -> X.to_string()

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust-clippy#8238] opened 2022-01-07 08:30 UTC
### What it does

Since many types support `to_string()` if `format!` is being used just to produce a string version then surely calling `to_string()` is better?

### Lint Name

Convert an item to a string

### Category

style

### Advantage

I assume that this would be more efficient. It looks nicer too.

### Example

```rust
    let year = Local::today().year();
    let year = if year == 2021 {
        format!("{}", year)
    } else {
        format!("2021-{}", year - 2000)
    };
```

Could be written as:

```rust
    let year = Local::today().year();
    let year = if year == 2021 {
        year.to_string()
    } else {
        format!("2021-{}", year - 2000)
    };
```

**Comment by giraffate** [comment] 2022-01-07 13:50
Do you mean the [`useless_format`](https://rust-lang.github.io/rust-clippy/master/index.html#useless_format) lint?

**Comment by mark-summerfield** [comment] 2022-01-07 17:23
No, it is different. The `useless_format` hint is where the `X` is a string; I'm talking about when it isn't a string but _does_ have a `to_string()` method, e.g., an `i32`.

**Comment by camsteffen** [comment] 2022-01-07 18:41
Duplicate of #3156

**Closed by camsteffen** 2022-01-07 18:41 UTC
Labels: A-lint
