### ISSUE TITLE
Compiler error on `clippy::redudant_clone` in async function call

### ISSUE THREAD

**Issue by Lut99** [rust-lang/rust-clippy#9847] opened 2022-11-14 11:36 UTC
Hi!

I've run into the compiler crashing when I attempt to run clippy on my project. The specific error appears to be:
```bash
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:626:9: type parameter `Self/#0` (Self/0) out of range when substituting, substs=[]
```

To reproduce, you can create a `main.rs` with the following:
```rust
pub async fn function(_argument: impl AsRef<str>) {}

#[tokio::main]
async fn main() {
    let argument: String = "Hello there!".into();
    function(argument.to_string()).await;
}
```
and a matching `Cargo.toml`:
```toml
[package]
name = "clippy-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread","macros"] }
```

Running `cargo clippy` then gives me the error, which occurs only if the function call is uncommented (so it seems to occur there). In full:
```bash
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:626:9: type parameter `Self/#0` (Self/0) out of range when substituting, substs=[]

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.65 (897e375 2022-11-02)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `clippy-test`
```
(I'm hoping the error is reproducible, but I can post with `RUST_BACKTRACE=1` as well)

The versions of the tools I'm using:
- rustc: `rustc 1.65.0 (897e37553 2022-11-02)`
- Cargo: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
- Clippy: `clippy 0.1.65 (897e375 2022-11-02)`

To be complete, I'm using the stable toolchain (unlike some other issues with panics I've seen on the first page).

Hopefully, this helps! If you need any more information, please let me know :)

**Comment by giraffate** [comment] 2022-11-15 00:07
Thanks for the report!

It's a duplicate of https://github.com/rust-lang/rust-clippy/issues/9504, so I'm closing this.

from https://github.com/rust-lang/rust-clippy/issues/9781#issuecomment-1314073946
> The fix for this hasn't made it to stable yet. From a quick check, it should be in beta and should get into 1.66 stable.

**Closed by giraffate** 2022-11-15 00:07 UTC
