### ISSUE TITLE
macro check for redundant_closure_call

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust-clippy#1639] opened 2017-03-26 21:48 UTC
libcore has a counter-example for redundant_closure_call: In str/pattern.rs,
a macro reuses type constructors as closures to create instances of Searchers
to easily abstract over Pattern types. A macro check would probably do good
here.

**Comment by clarcharr** [comment] 2017-04-05 20:30
duplicate of #1553 ?

**Comment by phansch** [comment] 2019-04-21 09:15
Closing as dup of #1553

**Closed by phansch** 2019-04-21 09:15 UTC
Labels: L-bug :beetle:, T-middle, good first issue, hacktoberfest
