### ISSUE TITLE
ICE "computing layout of"

### ISSUE THREAD

**Issue by lfrancke** [rust-lang/rust-clippy#6587] opened 2021-01-14 12:42 UTC
### Meta

- `Clippy version: clippy 0.1.51 (a62a760 2021-01-13)`
- `rustc 1.51.0-nightly (a62a76047 2021-01-13)`

### Error output

```
note: the compiler unexpectedly panicked. this is a bug.
  
  note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new
  
  note: Clippy version: clippy 0.1.51 (a62a760 2021-01-13)
  
  query stack during panic:
  #0 [optimized_mir] optimizing MIR for `kube::Api::<K>::get::{closure#0}`
  #1 [layout_raw] computing layout of `[static generator@kube::Api<T>::get::{closure#0} for<'r, 's, 't0, 't1> {std::future::ResumeTy, &'r kube::Api<T>, &'s str, k8s_openapi::http::Request<std::vec::Vec<u8>>, kube::Api<T>, &'t0 kube::Client, kube::Client, impl std::future::Future, ()}]`
  end of query stack
  {"reason":"compiler-message","package_id":"stackable-operator 0.1.0 (path+file:///home/runner/work/operator-rs/operator-rs)","target":{"kind":["lib"],"crate_types":["lib"],"name":"stackable-operator","src_path":"/home/runner/work/operator-rs/operator-rs/src/lib.rs","edition":"2018","doc":true,"doctest":true,"test":true},"message":{"rendered":"error: aborting due to previous error\n\n","children":[],"code":null,"level":"error","message":"aborting due to previous error","spans":[]}}
  {"reason":"build-finished","success":false}
```

Unfortunately, I don't have the time now to try and create a minimal example.
I therefore understand if this issue is closed without action.

I can however provide this link to the public Github Actions run that failed: https://github.com/stackabletech/operator-rs/runs/1701809866?check_suite_focus=true

This is the first time I hit an ICE (I even had to google what that means which isn't easy ;-) ).

**Comment by giraffate** [comment] 2021-01-14 23:51
Thanks for your report!

It seems to be a duplicate of https://github.com/rust-lang/rust-clippy/issues/6588, and https://github.com/rust-lang/rust-clippy/issues/6588 has more info, so I'm closing this.

**Closed by giraffate** 2021-01-14 23:51 UTC
Labels: L-bug, L-crash

**Comment by lfrancke** [comment] 2021-01-15 05:49
Thank you and sorry for the duplicate.

Takayuki Nakata <notifications@github.com> schrieb am Fr., 15. Jan. 2021,
00:51:
