### ISSUE TITLE
Suggest `use ... as _` if the type is used for traits calls only

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust-clippy#10606] opened 2023-04-07 17:11 UTC
### What it does

If a specific trait is brought into the scope just because it extends some type, but not used directly, alias it as an anonymous  `_`.  I have frequently seen it with the common for `std::io::Write`:

```
use std::io::Write as _;  // <-- don't introduce the "Write" trait into the scope

fn main() {
    std::io::stdout().write_all(b"Hello, world!").unwrap();
}
```

### Lint Name

use_non_polluting_alias_for_traits

### Advantage

- does not introduce (directly) unused traits into the scope

### Example

For trait methods like

```rust
mod ext {
    pub trait Foo {
        fn foo(&self) {
            println!("foo");
        }
    }

    impl Foo for i32 {}
}
```

This example
```rust
fn main() {
    use crate::ext::Foo;  // <- no aliasing, polluting
    42.foo();
}
```

Could be written as:

```rust
fn main() {
    use crate::ext::Foo as _; // non-polluting aliasing
    42.foo();
}
```

**Comment by Alexendoo** [comment] 2023-04-07 17:27
Duplicate of #9021

**Closed by Alexendoo** 2023-04-07 17:27 UTC
Labels: A-lint
