### ISSUE TITLE
len_without_is_empty triggers for async len methods, but does not accept async is_empty methods

### ISSUE THREAD

**Issue by zesterer** [rust-lang/rust-clippy#7232] opened 2021-05-17 12:34 UTC
The following will trigger the `len_without_is_empty` error:

```rust
impl Foo {
    pub async fn len(&self) -> usize { ... }
    pub async fn is_empty(&self) -> bool { ... }
}
```

It probably shouldn't expect the exact signature `fn(&self) -> bool`.

**Comment by hi-rustin** [comment] 2021-05-20 03:44
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=79bfeb9fffa256435a1e315490842554

I can't reproduce the issue on rust playground. Could you provide some steps to reproduce it?

**Comment by zesterer** [comment] 2021-05-24 09:41
Comment out `is_empty`. I see no warning. That implies to me that clippy isn't running on the snippet properly.

**Comment by giraffate** [comment] 2021-05-25 00:29
It seems to be fixed by https://github.com/rust-lang/rust-clippy/pull/6980.

**Comment by Jarcho** [comment] 2021-06-04 20:10
That change basically whitelisted the allowed types for `len` to an integral type, `Option`, or `Result`. Since async functions return `impl Future<Output=T>` they'll be slipped over. It's a thing I considered adding, just haven't had the time.

**Closed** 2023-03-09 17:29 UTC
Labels: C-bug, good-first-issue, I-false-positive
